// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bill_transaction.proto

package applicationtier.protobuf;

public final class BillTransaction {
  private BillTransaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BillPaymentProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BillPaymentProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    boolean hasBillPaymentId();
    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    com.google.protobuf.Int64Value getBillPaymentId();
    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getBillPaymentIdOrBuilder();

    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    boolean hasSenderUser();
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getSenderUser();
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder();

    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    boolean hasPayeeName();
    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    com.google.protobuf.StringValue getPayeeName();
    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    com.google.protobuf.StringValueOrBuilder getPayeeNameOrBuilder();

    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    boolean hasAmount();
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    com.google.protobuf.Int32Value getAmount();
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder();

    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    boolean hasAccountNumber();
    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    com.google.protobuf.StringValue getAccountNumber();
    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    com.google.protobuf.StringValueOrBuilder getAccountNumberOrBuilder();

    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    boolean hasDate();
    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    com.google.protobuf.StringValue getDate();
    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    com.google.protobuf.StringValueOrBuilder getDateOrBuilder();

    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    boolean hasReference();
    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    com.google.protobuf.StringValue getReference();
    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    com.google.protobuf.StringValueOrBuilder getReferenceOrBuilder();
  }
  /**
   * Protobuf type {@code BillPaymentProtoObj}
   */
  public  static final class BillPaymentProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BillPaymentProtoObj)
      BillPaymentProtoObjOrBuilder {
    // Use BillPaymentProtoObj.newBuilder() to construct.
    private BillPaymentProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BillPaymentProtoObj() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BillPaymentProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (billPaymentId_ != null) {
                subBuilder = billPaymentId_.toBuilder();
              }
              billPaymentId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(billPaymentId_);
                billPaymentId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              applicationtier.protobuf.User.UserProtoObj.Builder subBuilder = null;
              if (senderUser_ != null) {
                subBuilder = senderUser_.toBuilder();
              }
              senderUser_ = input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(senderUser_);
                senderUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (payeeName_ != null) {
                subBuilder = payeeName_.toBuilder();
              }
              payeeName_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payeeName_);
                payeeName_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (amount_ != null) {
                subBuilder = amount_.toBuilder();
              }
              amount_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(amount_);
                amount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (accountNumber_ != null) {
                subBuilder = accountNumber_.toBuilder();
              }
              accountNumber_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(accountNumber_);
                accountNumber_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (date_ != null) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (reference_ != null) {
                subBuilder = reference_.toBuilder();
              }
              reference_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(reference_);
                reference_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.class, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder.class);
    }

    public static final int BILLPAYMENT_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Int64Value billPaymentId_;
    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    public boolean hasBillPaymentId() {
      return billPaymentId_ != null;
    }
    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    public com.google.protobuf.Int64Value getBillPaymentId() {
      return billPaymentId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : billPaymentId_;
    }
    /**
     * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getBillPaymentIdOrBuilder() {
      return getBillPaymentId();
    }

    public static final int SENDERUSER_FIELD_NUMBER = 2;
    private applicationtier.protobuf.User.UserProtoObj senderUser_;
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public boolean hasSenderUser() {
      return senderUser_ != null;
    }
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getSenderUser() {
      return senderUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
    }
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder() {
      return getSenderUser();
    }

    public static final int PAYEENAME_FIELD_NUMBER = 3;
    private com.google.protobuf.StringValue payeeName_;
    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    public boolean hasPayeeName() {
      return payeeName_ != null;
    }
    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    public com.google.protobuf.StringValue getPayeeName() {
      return payeeName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : payeeName_;
    }
    /**
     * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getPayeeNameOrBuilder() {
      return getPayeeName();
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private com.google.protobuf.Int32Value amount_;
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public com.google.protobuf.Int32Value getAmount() {
      return amount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
    }
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder() {
      return getAmount();
    }

    public static final int ACCOUNTNUMBER_FIELD_NUMBER = 5;
    private com.google.protobuf.StringValue accountNumber_;
    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    public boolean hasAccountNumber() {
      return accountNumber_ != null;
    }
    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    public com.google.protobuf.StringValue getAccountNumber() {
      return accountNumber_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : accountNumber_;
    }
    /**
     * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getAccountNumberOrBuilder() {
      return getAccountNumber();
    }

    public static final int DATE_FIELD_NUMBER = 6;
    private com.google.protobuf.StringValue date_;
    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    public com.google.protobuf.StringValue getDate() {
      return date_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : date_;
    }
    /**
     * <code>optional .google.protobuf.StringValue date = 6;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDateOrBuilder() {
      return getDate();
    }

    public static final int REFERENCE_FIELD_NUMBER = 7;
    private com.google.protobuf.StringValue reference_;
    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    public boolean hasReference() {
      return reference_ != null;
    }
    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    public com.google.protobuf.StringValue getReference() {
      return reference_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : reference_;
    }
    /**
     * <code>optional .google.protobuf.StringValue reference = 7;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getReferenceOrBuilder() {
      return getReference();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (billPaymentId_ != null) {
        output.writeMessage(1, getBillPaymentId());
      }
      if (senderUser_ != null) {
        output.writeMessage(2, getSenderUser());
      }
      if (payeeName_ != null) {
        output.writeMessage(3, getPayeeName());
      }
      if (amount_ != null) {
        output.writeMessage(4, getAmount());
      }
      if (accountNumber_ != null) {
        output.writeMessage(5, getAccountNumber());
      }
      if (date_ != null) {
        output.writeMessage(6, getDate());
      }
      if (reference_ != null) {
        output.writeMessage(7, getReference());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (billPaymentId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBillPaymentId());
      }
      if (senderUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSenderUser());
      }
      if (payeeName_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPayeeName());
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAmount());
      }
      if (accountNumber_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAccountNumber());
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDate());
      }
      if (reference_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getReference());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.BillTransaction.BillPaymentProtoObj)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.BillTransaction.BillPaymentProtoObj other = (applicationtier.protobuf.BillTransaction.BillPaymentProtoObj) obj;

      boolean result = true;
      result = result && (hasBillPaymentId() == other.hasBillPaymentId());
      if (hasBillPaymentId()) {
        result = result && getBillPaymentId()
            .equals(other.getBillPaymentId());
      }
      result = result && (hasSenderUser() == other.hasSenderUser());
      if (hasSenderUser()) {
        result = result && getSenderUser()
            .equals(other.getSenderUser());
      }
      result = result && (hasPayeeName() == other.hasPayeeName());
      if (hasPayeeName()) {
        result = result && getPayeeName()
            .equals(other.getPayeeName());
      }
      result = result && (hasAmount() == other.hasAmount());
      if (hasAmount()) {
        result = result && getAmount()
            .equals(other.getAmount());
      }
      result = result && (hasAccountNumber() == other.hasAccountNumber());
      if (hasAccountNumber()) {
        result = result && getAccountNumber()
            .equals(other.getAccountNumber());
      }
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && (hasReference() == other.hasReference());
      if (hasReference()) {
        result = result && getReference()
            .equals(other.getReference());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBillPaymentId()) {
        hash = (37 * hash) + BILLPAYMENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getBillPaymentId().hashCode();
      }
      if (hasSenderUser()) {
        hash = (37 * hash) + SENDERUSER_FIELD_NUMBER;
        hash = (53 * hash) + getSenderUser().hashCode();
      }
      if (hasPayeeName()) {
        hash = (37 * hash) + PAYEENAME_FIELD_NUMBER;
        hash = (53 * hash) + getPayeeName().hashCode();
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      if (hasAccountNumber()) {
        hash = (37 * hash) + ACCOUNTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getAccountNumber().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasReference()) {
        hash = (37 * hash) + REFERENCE_FIELD_NUMBER;
        hash = (53 * hash) + getReference().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.BillTransaction.BillPaymentProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BillPaymentProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BillPaymentProtoObj)
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.class, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder.class);
      }

      // Construct using applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (billPaymentIdBuilder_ == null) {
          billPaymentId_ = null;
        } else {
          billPaymentId_ = null;
          billPaymentIdBuilder_ = null;
        }
        if (senderUserBuilder_ == null) {
          senderUser_ = null;
        } else {
          senderUser_ = null;
          senderUserBuilder_ = null;
        }
        if (payeeNameBuilder_ == null) {
          payeeName_ = null;
        } else {
          payeeName_ = null;
          payeeNameBuilder_ = null;
        }
        if (amountBuilder_ == null) {
          amount_ = null;
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }
        if (accountNumberBuilder_ == null) {
          accountNumber_ = null;
        } else {
          accountNumber_ = null;
          accountNumberBuilder_ = null;
        }
        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          date_ = null;
          dateBuilder_ = null;
        }
        if (referenceBuilder_ == null) {
          reference_ = null;
        } else {
          reference_ = null;
          referenceBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObj_descriptor;
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getDefaultInstanceForType() {
        return applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.getDefaultInstance();
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj build() {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj buildPartial() {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObj result = new applicationtier.protobuf.BillTransaction.BillPaymentProtoObj(this);
        if (billPaymentIdBuilder_ == null) {
          result.billPaymentId_ = billPaymentId_;
        } else {
          result.billPaymentId_ = billPaymentIdBuilder_.build();
        }
        if (senderUserBuilder_ == null) {
          result.senderUser_ = senderUser_;
        } else {
          result.senderUser_ = senderUserBuilder_.build();
        }
        if (payeeNameBuilder_ == null) {
          result.payeeName_ = payeeName_;
        } else {
          result.payeeName_ = payeeNameBuilder_.build();
        }
        if (amountBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = amountBuilder_.build();
        }
        if (accountNumberBuilder_ == null) {
          result.accountNumber_ = accountNumber_;
        } else {
          result.accountNumber_ = accountNumberBuilder_.build();
        }
        if (dateBuilder_ == null) {
          result.date_ = date_;
        } else {
          result.date_ = dateBuilder_.build();
        }
        if (referenceBuilder_ == null) {
          result.reference_ = reference_;
        } else {
          result.reference_ = referenceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.BillTransaction.BillPaymentProtoObj) {
          return mergeFrom((applicationtier.protobuf.BillTransaction.BillPaymentProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.BillTransaction.BillPaymentProtoObj other) {
        if (other == applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.getDefaultInstance()) return this;
        if (other.hasBillPaymentId()) {
          mergeBillPaymentId(other.getBillPaymentId());
        }
        if (other.hasSenderUser()) {
          mergeSenderUser(other.getSenderUser());
        }
        if (other.hasPayeeName()) {
          mergePayeeName(other.getPayeeName());
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        if (other.hasAccountNumber()) {
          mergeAccountNumber(other.getAccountNumber());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        if (other.hasReference()) {
          mergeReference(other.getReference());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.BillTransaction.BillPaymentProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Int64Value billPaymentId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> billPaymentIdBuilder_;
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public boolean hasBillPaymentId() {
        return billPaymentIdBuilder_ != null || billPaymentId_ != null;
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public com.google.protobuf.Int64Value getBillPaymentId() {
        if (billPaymentIdBuilder_ == null) {
          return billPaymentId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : billPaymentId_;
        } else {
          return billPaymentIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public Builder setBillPaymentId(com.google.protobuf.Int64Value value) {
        if (billPaymentIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          billPaymentId_ = value;
          onChanged();
        } else {
          billPaymentIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public Builder setBillPaymentId(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (billPaymentIdBuilder_ == null) {
          billPaymentId_ = builderForValue.build();
          onChanged();
        } else {
          billPaymentIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public Builder mergeBillPaymentId(com.google.protobuf.Int64Value value) {
        if (billPaymentIdBuilder_ == null) {
          if (billPaymentId_ != null) {
            billPaymentId_ =
              com.google.protobuf.Int64Value.newBuilder(billPaymentId_).mergeFrom(value).buildPartial();
          } else {
            billPaymentId_ = value;
          }
          onChanged();
        } else {
          billPaymentIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public Builder clearBillPaymentId() {
        if (billPaymentIdBuilder_ == null) {
          billPaymentId_ = null;
          onChanged();
        } else {
          billPaymentId_ = null;
          billPaymentIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public com.google.protobuf.Int64Value.Builder getBillPaymentIdBuilder() {
        
        onChanged();
        return getBillPaymentIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getBillPaymentIdOrBuilder() {
        if (billPaymentIdBuilder_ != null) {
          return billPaymentIdBuilder_.getMessageOrBuilder();
        } else {
          return billPaymentId_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : billPaymentId_;
        }
      }
      /**
       * <code>optional .google.protobuf.Int64Value BillPayment_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getBillPaymentIdFieldBuilder() {
        if (billPaymentIdBuilder_ == null) {
          billPaymentIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getBillPaymentId(),
                  getParentForChildren(),
                  isClean());
          billPaymentId_ = null;
        }
        return billPaymentIdBuilder_;
      }

      private applicationtier.protobuf.User.UserProtoObj senderUser_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> senderUserBuilder_;
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public boolean hasSenderUser() {
        return senderUserBuilder_ != null || senderUser_ != null;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getSenderUser() {
        if (senderUserBuilder_ == null) {
          return senderUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
        } else {
          return senderUserBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder setSenderUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (senderUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          senderUser_ = value;
          onChanged();
        } else {
          senderUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder setSenderUser(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (senderUserBuilder_ == null) {
          senderUser_ = builderForValue.build();
          onChanged();
        } else {
          senderUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder mergeSenderUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (senderUserBuilder_ == null) {
          if (senderUser_ != null) {
            senderUser_ =
              applicationtier.protobuf.User.UserProtoObj.newBuilder(senderUser_).mergeFrom(value).buildPartial();
          } else {
            senderUser_ = value;
          }
          onChanged();
        } else {
          senderUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder clearSenderUser() {
        if (senderUserBuilder_ == null) {
          senderUser_ = null;
          onChanged();
        } else {
          senderUser_ = null;
          senderUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getSenderUserBuilder() {
        
        onChanged();
        return getSenderUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder() {
        if (senderUserBuilder_ != null) {
          return senderUserBuilder_.getMessageOrBuilder();
        } else {
          return senderUser_ == null ?
              applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
        }
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getSenderUserFieldBuilder() {
        if (senderUserBuilder_ == null) {
          senderUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  getSenderUser(),
                  getParentForChildren(),
                  isClean());
          senderUser_ = null;
        }
        return senderUserBuilder_;
      }

      private com.google.protobuf.StringValue payeeName_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> payeeNameBuilder_;
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public boolean hasPayeeName() {
        return payeeNameBuilder_ != null || payeeName_ != null;
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public com.google.protobuf.StringValue getPayeeName() {
        if (payeeNameBuilder_ == null) {
          return payeeName_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : payeeName_;
        } else {
          return payeeNameBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public Builder setPayeeName(com.google.protobuf.StringValue value) {
        if (payeeNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payeeName_ = value;
          onChanged();
        } else {
          payeeNameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public Builder setPayeeName(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (payeeNameBuilder_ == null) {
          payeeName_ = builderForValue.build();
          onChanged();
        } else {
          payeeNameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public Builder mergePayeeName(com.google.protobuf.StringValue value) {
        if (payeeNameBuilder_ == null) {
          if (payeeName_ != null) {
            payeeName_ =
              com.google.protobuf.StringValue.newBuilder(payeeName_).mergeFrom(value).buildPartial();
          } else {
            payeeName_ = value;
          }
          onChanged();
        } else {
          payeeNameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public Builder clearPayeeName() {
        if (payeeNameBuilder_ == null) {
          payeeName_ = null;
          onChanged();
        } else {
          payeeName_ = null;
          payeeNameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public com.google.protobuf.StringValue.Builder getPayeeNameBuilder() {
        
        onChanged();
        return getPayeeNameFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getPayeeNameOrBuilder() {
        if (payeeNameBuilder_ != null) {
          return payeeNameBuilder_.getMessageOrBuilder();
        } else {
          return payeeName_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : payeeName_;
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue payeeName = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getPayeeNameFieldBuilder() {
        if (payeeNameBuilder_ == null) {
          payeeNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getPayeeName(),
                  getParentForChildren(),
                  isClean());
          payeeName_ = null;
        }
        return payeeNameBuilder_;
      }

      private com.google.protobuf.Int32Value amount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> amountBuilder_;
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public boolean hasAmount() {
        return amountBuilder_ != null || amount_ != null;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32Value getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder setAmount(com.google.protobuf.Int32Value value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
          onChanged();
        } else {
          amountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder setAmount(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
          onChanged();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder mergeAmount(com.google.protobuf.Int32Value value) {
        if (amountBuilder_ == null) {
          if (amount_ != null) {
            amount_ =
              com.google.protobuf.Int32Value.newBuilder(amount_).mergeFrom(value).buildPartial();
          } else {
            amount_ = value;
          }
          onChanged();
        } else {
          amountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder clearAmount() {
        if (amountBuilder_ == null) {
          amount_ = null;
          onChanged();
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32Value.Builder getAmountBuilder() {
        
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }

      private com.google.protobuf.StringValue accountNumber_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> accountNumberBuilder_;
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public boolean hasAccountNumber() {
        return accountNumberBuilder_ != null || accountNumber_ != null;
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public com.google.protobuf.StringValue getAccountNumber() {
        if (accountNumberBuilder_ == null) {
          return accountNumber_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : accountNumber_;
        } else {
          return accountNumberBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public Builder setAccountNumber(com.google.protobuf.StringValue value) {
        if (accountNumberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          accountNumber_ = value;
          onChanged();
        } else {
          accountNumberBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public Builder setAccountNumber(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (accountNumberBuilder_ == null) {
          accountNumber_ = builderForValue.build();
          onChanged();
        } else {
          accountNumberBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public Builder mergeAccountNumber(com.google.protobuf.StringValue value) {
        if (accountNumberBuilder_ == null) {
          if (accountNumber_ != null) {
            accountNumber_ =
              com.google.protobuf.StringValue.newBuilder(accountNumber_).mergeFrom(value).buildPartial();
          } else {
            accountNumber_ = value;
          }
          onChanged();
        } else {
          accountNumberBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public Builder clearAccountNumber() {
        if (accountNumberBuilder_ == null) {
          accountNumber_ = null;
          onChanged();
        } else {
          accountNumber_ = null;
          accountNumberBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public com.google.protobuf.StringValue.Builder getAccountNumberBuilder() {
        
        onChanged();
        return getAccountNumberFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getAccountNumberOrBuilder() {
        if (accountNumberBuilder_ != null) {
          return accountNumberBuilder_.getMessageOrBuilder();
        } else {
          return accountNumber_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : accountNumber_;
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue accountNumber = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getAccountNumberFieldBuilder() {
        if (accountNumberBuilder_ == null) {
          accountNumberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getAccountNumber(),
                  getParentForChildren(),
                  isClean());
          accountNumber_ = null;
        }
        return accountNumberBuilder_;
      }

      private com.google.protobuf.StringValue date_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> dateBuilder_;
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public boolean hasDate() {
        return dateBuilder_ != null || date_ != null;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public com.google.protobuf.StringValue getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public Builder setDate(com.google.protobuf.StringValue value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public Builder setDate(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public Builder mergeDate(com.google.protobuf.StringValue value) {
        if (dateBuilder_ == null) {
          if (date_ != null) {
            date_ =
              com.google.protobuf.StringValue.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          date_ = null;
          dateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public com.google.protobuf.StringValue.Builder getDateBuilder() {
        
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      private com.google.protobuf.StringValue reference_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> referenceBuilder_;
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public boolean hasReference() {
        return referenceBuilder_ != null || reference_ != null;
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public com.google.protobuf.StringValue getReference() {
        if (referenceBuilder_ == null) {
          return reference_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : reference_;
        } else {
          return referenceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public Builder setReference(com.google.protobuf.StringValue value) {
        if (referenceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          reference_ = value;
          onChanged();
        } else {
          referenceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public Builder setReference(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (referenceBuilder_ == null) {
          reference_ = builderForValue.build();
          onChanged();
        } else {
          referenceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public Builder mergeReference(com.google.protobuf.StringValue value) {
        if (referenceBuilder_ == null) {
          if (reference_ != null) {
            reference_ =
              com.google.protobuf.StringValue.newBuilder(reference_).mergeFrom(value).buildPartial();
          } else {
            reference_ = value;
          }
          onChanged();
        } else {
          referenceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public Builder clearReference() {
        if (referenceBuilder_ == null) {
          reference_ = null;
          onChanged();
        } else {
          reference_ = null;
          referenceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public com.google.protobuf.StringValue.Builder getReferenceBuilder() {
        
        onChanged();
        return getReferenceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getReferenceOrBuilder() {
        if (referenceBuilder_ != null) {
          return referenceBuilder_.getMessageOrBuilder();
        } else {
          return reference_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : reference_;
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue reference = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getReferenceFieldBuilder() {
        if (referenceBuilder_ == null) {
          referenceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getReference(),
                  getParentForChildren(),
                  isClean());
          reference_ = null;
        }
        return referenceBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BillPaymentProtoObj)
    }

    // @@protoc_insertion_point(class_scope:BillPaymentProtoObj)
    private static final applicationtier.protobuf.BillTransaction.BillPaymentProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.BillTransaction.BillPaymentProtoObj();
    }

    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BillPaymentProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<BillPaymentProtoObj>() {
      public BillPaymentProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BillPaymentProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BillPaymentProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BillPaymentProtoObj> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BillPaymentProtoObjListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BillPaymentProtoObjList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> 
        getAllBillPaymentsList();
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getAllBillPayments(int index);
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    int getAllBillPaymentsCount();
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    java.util.List<? extends applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder> 
        getAllBillPaymentsOrBuilderList();
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder getAllBillPaymentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code BillPaymentProtoObjList}
   */
  public  static final class BillPaymentProtoObjList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BillPaymentProtoObjList)
      BillPaymentProtoObjListOrBuilder {
    // Use BillPaymentProtoObjList.newBuilder() to construct.
    private BillPaymentProtoObjList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BillPaymentProtoObjList() {
      allBillPayments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BillPaymentProtoObjList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allBillPayments_ = new java.util.ArrayList<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allBillPayments_.add(
                  input.readMessage(applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allBillPayments_ = java.util.Collections.unmodifiableList(allBillPayments_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObjList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObjList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.class, applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.Builder.class);
    }

    public static final int ALLBILLPAYMENTS_FIELD_NUMBER = 1;
    private java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> allBillPayments_;
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    public java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> getAllBillPaymentsList() {
      return allBillPayments_;
    }
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    public java.util.List<? extends applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder> 
        getAllBillPaymentsOrBuilderList() {
      return allBillPayments_;
    }
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    public int getAllBillPaymentsCount() {
      return allBillPayments_.size();
    }
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getAllBillPayments(int index) {
      return allBillPayments_.get(index);
    }
    /**
     * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
     */
    public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder getAllBillPaymentsOrBuilder(
        int index) {
      return allBillPayments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allBillPayments_.size(); i++) {
        output.writeMessage(1, allBillPayments_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allBillPayments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allBillPayments_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList other = (applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList) obj;

      boolean result = true;
      result = result && getAllBillPaymentsList()
          .equals(other.getAllBillPaymentsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAllBillPaymentsCount() > 0) {
        hash = (37 * hash) + ALLBILLPAYMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAllBillPaymentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BillPaymentProtoObjList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BillPaymentProtoObjList)
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObjListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObjList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObjList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.class, applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.Builder.class);
      }

      // Construct using applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllBillPaymentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (allBillPaymentsBuilder_ == null) {
          allBillPayments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allBillPaymentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.BillTransaction.internal_static_BillPaymentProtoObjList_descriptor;
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList getDefaultInstanceForType() {
        return applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.getDefaultInstance();
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList build() {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList buildPartial() {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList result = new applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList(this);
        int from_bitField0_ = bitField0_;
        if (allBillPaymentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allBillPayments_ = java.util.Collections.unmodifiableList(allBillPayments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allBillPayments_ = allBillPayments_;
        } else {
          result.allBillPayments_ = allBillPaymentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList) {
          return mergeFrom((applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList other) {
        if (other == applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList.getDefaultInstance()) return this;
        if (allBillPaymentsBuilder_ == null) {
          if (!other.allBillPayments_.isEmpty()) {
            if (allBillPayments_.isEmpty()) {
              allBillPayments_ = other.allBillPayments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllBillPaymentsIsMutable();
              allBillPayments_.addAll(other.allBillPayments_);
            }
            onChanged();
          }
        } else {
          if (!other.allBillPayments_.isEmpty()) {
            if (allBillPaymentsBuilder_.isEmpty()) {
              allBillPaymentsBuilder_.dispose();
              allBillPaymentsBuilder_ = null;
              allBillPayments_ = other.allBillPayments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allBillPaymentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllBillPaymentsFieldBuilder() : null;
            } else {
              allBillPaymentsBuilder_.addAllMessages(other.allBillPayments_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> allBillPayments_ =
        java.util.Collections.emptyList();
      private void ensureAllBillPaymentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allBillPayments_ = new java.util.ArrayList<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj>(allBillPayments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.BillTransaction.BillPaymentProtoObj, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder, applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder> allBillPaymentsBuilder_;

      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> getAllBillPaymentsList() {
        if (allBillPaymentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allBillPayments_);
        } else {
          return allBillPaymentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public int getAllBillPaymentsCount() {
        if (allBillPaymentsBuilder_ == null) {
          return allBillPayments_.size();
        } else {
          return allBillPaymentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj getAllBillPayments(int index) {
        if (allBillPaymentsBuilder_ == null) {
          return allBillPayments_.get(index);
        } else {
          return allBillPaymentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder setAllBillPayments(
          int index, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj value) {
        if (allBillPaymentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.set(index, value);
          onChanged();
        } else {
          allBillPaymentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder setAllBillPayments(
          int index, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder builderForValue) {
        if (allBillPaymentsBuilder_ == null) {
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.set(index, builderForValue.build());
          onChanged();
        } else {
          allBillPaymentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder addAllBillPayments(applicationtier.protobuf.BillTransaction.BillPaymentProtoObj value) {
        if (allBillPaymentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.add(value);
          onChanged();
        } else {
          allBillPaymentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder addAllBillPayments(
          int index, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj value) {
        if (allBillPaymentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.add(index, value);
          onChanged();
        } else {
          allBillPaymentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder addAllBillPayments(
          applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder builderForValue) {
        if (allBillPaymentsBuilder_ == null) {
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.add(builderForValue.build());
          onChanged();
        } else {
          allBillPaymentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder addAllBillPayments(
          int index, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder builderForValue) {
        if (allBillPaymentsBuilder_ == null) {
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.add(index, builderForValue.build());
          onChanged();
        } else {
          allBillPaymentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder addAllAllBillPayments(
          java.lang.Iterable<? extends applicationtier.protobuf.BillTransaction.BillPaymentProtoObj> values) {
        if (allBillPaymentsBuilder_ == null) {
          ensureAllBillPaymentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allBillPayments_);
          onChanged();
        } else {
          allBillPaymentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder clearAllBillPayments() {
        if (allBillPaymentsBuilder_ == null) {
          allBillPayments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allBillPaymentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public Builder removeAllBillPayments(int index) {
        if (allBillPaymentsBuilder_ == null) {
          ensureAllBillPaymentsIsMutable();
          allBillPayments_.remove(index);
          onChanged();
        } else {
          allBillPaymentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder getAllBillPaymentsBuilder(
          int index) {
        return getAllBillPaymentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder getAllBillPaymentsOrBuilder(
          int index) {
        if (allBillPaymentsBuilder_ == null) {
          return allBillPayments_.get(index);  } else {
          return allBillPaymentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public java.util.List<? extends applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder> 
           getAllBillPaymentsOrBuilderList() {
        if (allBillPaymentsBuilder_ != null) {
          return allBillPaymentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allBillPayments_);
        }
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder addAllBillPaymentsBuilder() {
        return getAllBillPaymentsFieldBuilder().addBuilder(
            applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder addAllBillPaymentsBuilder(
          int index) {
        return getAllBillPaymentsFieldBuilder().addBuilder(
            index, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .BillPaymentProtoObj allBillPayments = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder> 
           getAllBillPaymentsBuilderList() {
        return getAllBillPaymentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.BillTransaction.BillPaymentProtoObj, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder, applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder> 
          getAllBillPaymentsFieldBuilder() {
        if (allBillPaymentsBuilder_ == null) {
          allBillPaymentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              applicationtier.protobuf.BillTransaction.BillPaymentProtoObj, applicationtier.protobuf.BillTransaction.BillPaymentProtoObj.Builder, applicationtier.protobuf.BillTransaction.BillPaymentProtoObjOrBuilder>(
                  allBillPayments_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allBillPayments_ = null;
        }
        return allBillPaymentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BillPaymentProtoObjList)
    }

    // @@protoc_insertion_point(class_scope:BillPaymentProtoObjList)
    private static final applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList();
    }

    public static applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BillPaymentProtoObjList>
        PARSER = new com.google.protobuf.AbstractParser<BillPaymentProtoObjList>() {
      public BillPaymentProtoObjList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BillPaymentProtoObjList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BillPaymentProtoObjList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BillPaymentProtoObjList> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.BillTransaction.BillPaymentProtoObjList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BillPaymentProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BillPaymentProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BillPaymentProtoObjList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BillPaymentProtoObjList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026bill_transaction.proto\032\036google/protobu" +
      "f/wrappers.proto\032\nuser.proto\032\033google/pro" +
      "tobuf/empty.proto\"\335\002\n\023BillPaymentProtoOb" +
      "j\0223\n\016BillPayment_id\030\001 \001(\0132\033.google.proto" +
      "buf.Int64Value\022!\n\nsenderUser\030\002 \001(\0132\r.Use" +
      "rProtoObj\022/\n\tpayeeName\030\003 \001(\0132\034.google.pr" +
      "otobuf.StringValue\022+\n\006amount\030\004 \001(\0132\033.goo" +
      "gle.protobuf.Int32Value\0223\n\raccountNumber" +
      "\030\005 \001(\0132\034.google.protobuf.StringValue\022*\n\004" +
      "date\030\006 \001(\0132\034.google.protobuf.StringValue",
      "\022/\n\treference\030\007 \001(\0132\034.google.protobuf.St" +
      "ringValue\"H\n\027BillPaymentProtoObjList\022-\n\017" +
      "allBillPayments\030\001 \003(\0132\024.BillPaymentProto" +
      "Obj2\370\004\n\027BillPaymentProtoService\022D\n\026Creat" +
      "eBillPaymentAsync\022\024.BillPaymentProtoObj\032" +
      "\024.BillPaymentProtoObj\022N\n\031FetchBillPaymen" +
      "tByIdAsync\022\033.google.protobuf.Int64Value\032" +
      "\024.BillPaymentProtoObj\022[\n!FetchAlLBillPay" +
      "mentsBySenderAsync\022\034.google.protobuf.Str" +
      "ingValue\032\030.BillPaymentProtoObjList\022]\n#Fe",
      "tchAllBillPaymentsByReceiverAsync\022\034.goog" +
      "le.protobuf.StringValue\032\030.BillPaymentPro" +
      "toObjList\022`\n&FetchAlLBillPaymentsInvolvi" +
      "ngUserAsync\022\034.google.protobuf.StringValu" +
      "e\032\030.BillPaymentProtoObjList\022V\n\034FetchBill" +
      "PaymentsByDateAsync\022\034.google.protobuf.St" +
      "ringValue\032\030.BillPaymentProtoObjList\022Q\n\026D" +
      "eleteBillPaymentAsync\022\033.google.protobuf." +
      "Int64Value\032\032.google.protobuf.BoolValueB\034" +
      "\n\030applicationtier.protobufP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          applicationtier.protobuf.User.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_BillPaymentProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BillPaymentProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BillPaymentProtoObj_descriptor,
        new java.lang.String[] { "BillPaymentId", "SenderUser", "PayeeName", "Amount", "AccountNumber", "Date", "Reference", });
    internal_static_BillPaymentProtoObjList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BillPaymentProtoObjList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BillPaymentProtoObjList_descriptor,
        new java.lang.String[] { "AllBillPayments", });
    com.google.protobuf.WrappersProto.getDescriptor();
    applicationtier.protobuf.User.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
