// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: debitcard.proto

package applicationtier.protobuf;

public final class Debitcard {
  private Debitcard() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DebitCardProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DebitCardProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 card_id = 1;</code>
     */
    long getCardId();

    /**
     * <code>optional int64 card_number = 2;</code>
     */
    long getCardNumber();

    /**
     * <code>optional string expiry_date = 3;</code>
     */
    java.lang.String getExpiryDate();
    /**
     * <code>optional string expiry_date = 3;</code>
     */
    com.google.protobuf.ByteString
        getExpiryDateBytes();

    /**
     * <code>optional int32 cvv = 4;</code>
     */
    int getCvv();
  }
  /**
   * Protobuf type {@code DebitCardProtoObj}
   */
  public  static final class DebitCardProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DebitCardProtoObj)
      DebitCardProtoObjOrBuilder {
    // Use DebitCardProtoObj.newBuilder() to construct.
    private DebitCardProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DebitCardProtoObj() {
      cardId_ = 0L;
      cardNumber_ = 0L;
      expiryDate_ = "";
      cvv_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DebitCardProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cardId_ = input.readInt64();
              break;
            }
            case 16: {

              cardNumber_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              expiryDate_ = s;
              break;
            }
            case 32: {

              cvv_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Debitcard.internal_static_DebitCardProtoObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Debitcard.internal_static_DebitCardProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.class, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder.class);
    }

    public static final int CARD_ID_FIELD_NUMBER = 1;
    private long cardId_;
    /**
     * <code>optional int64 card_id = 1;</code>
     */
    public long getCardId() {
      return cardId_;
    }

    public static final int CARD_NUMBER_FIELD_NUMBER = 2;
    private long cardNumber_;
    /**
     * <code>optional int64 card_number = 2;</code>
     */
    public long getCardNumber() {
      return cardNumber_;
    }

    public static final int EXPIRY_DATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object expiryDate_;
    /**
     * <code>optional string expiry_date = 3;</code>
     */
    public java.lang.String getExpiryDate() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiryDate_ = s;
        return s;
      }
    }
    /**
     * <code>optional string expiry_date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExpiryDateBytes() {
      java.lang.Object ref = expiryDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiryDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CVV_FIELD_NUMBER = 4;
    private int cvv_;
    /**
     * <code>optional int32 cvv = 4;</code>
     */
    public int getCvv() {
      return cvv_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardId_ != 0L) {
        output.writeInt64(1, cardId_);
      }
      if (cardNumber_ != 0L) {
        output.writeInt64(2, cardNumber_);
      }
      if (!getExpiryDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, expiryDate_);
      }
      if (cvv_ != 0) {
        output.writeInt32(4, cvv_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cardId_);
      }
      if (cardNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cardNumber_);
      }
      if (!getExpiryDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, expiryDate_);
      }
      if (cvv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cvv_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Debitcard.DebitCardProtoObj)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Debitcard.DebitCardProtoObj other = (applicationtier.protobuf.Debitcard.DebitCardProtoObj) obj;

      boolean result = true;
      result = result && (getCardId()
          == other.getCardId());
      result = result && (getCardNumber()
          == other.getCardNumber());
      result = result && getExpiryDate()
          .equals(other.getExpiryDate());
      result = result && (getCvv()
          == other.getCvv());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CARD_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCardId());
      hash = (37 * hash) + CARD_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCardNumber());
      hash = (37 * hash) + EXPIRY_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpiryDate().hashCode();
      hash = (37 * hash) + CVV_FIELD_NUMBER;
      hash = (53 * hash) + getCvv();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Debitcard.DebitCardProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DebitCardProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DebitCardProtoObj)
        applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Debitcard.internal_static_DebitCardProtoObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Debitcard.internal_static_DebitCardProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Debitcard.DebitCardProtoObj.class, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder.class);
      }

      // Construct using applicationtier.protobuf.Debitcard.DebitCardProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardId_ = 0L;

        cardNumber_ = 0L;

        expiryDate_ = "";

        cvv_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Debitcard.internal_static_DebitCardProtoObj_descriptor;
      }

      public applicationtier.protobuf.Debitcard.DebitCardProtoObj getDefaultInstanceForType() {
        return applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance();
      }

      public applicationtier.protobuf.Debitcard.DebitCardProtoObj build() {
        applicationtier.protobuf.Debitcard.DebitCardProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Debitcard.DebitCardProtoObj buildPartial() {
        applicationtier.protobuf.Debitcard.DebitCardProtoObj result = new applicationtier.protobuf.Debitcard.DebitCardProtoObj(this);
        result.cardId_ = cardId_;
        result.cardNumber_ = cardNumber_;
        result.expiryDate_ = expiryDate_;
        result.cvv_ = cvv_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Debitcard.DebitCardProtoObj) {
          return mergeFrom((applicationtier.protobuf.Debitcard.DebitCardProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Debitcard.DebitCardProtoObj other) {
        if (other == applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance()) return this;
        if (other.getCardId() != 0L) {
          setCardId(other.getCardId());
        }
        if (other.getCardNumber() != 0L) {
          setCardNumber(other.getCardNumber());
        }
        if (!other.getExpiryDate().isEmpty()) {
          expiryDate_ = other.expiryDate_;
          onChanged();
        }
        if (other.getCvv() != 0) {
          setCvv(other.getCvv());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Debitcard.DebitCardProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Debitcard.DebitCardProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cardId_ ;
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public long getCardId() {
        return cardId_;
      }
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public Builder setCardId(long value) {
        
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = 0L;
        onChanged();
        return this;
      }

      private long cardNumber_ ;
      /**
       * <code>optional int64 card_number = 2;</code>
       */
      public long getCardNumber() {
        return cardNumber_;
      }
      /**
       * <code>optional int64 card_number = 2;</code>
       */
      public Builder setCardNumber(long value) {
        
        cardNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 card_number = 2;</code>
       */
      public Builder clearCardNumber() {
        
        cardNumber_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object expiryDate_ = "";
      /**
       * <code>optional string expiry_date = 3;</code>
       */
      public java.lang.String getExpiryDate() {
        java.lang.Object ref = expiryDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiryDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string expiry_date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExpiryDateBytes() {
        java.lang.Object ref = expiryDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiryDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string expiry_date = 3;</code>
       */
      public Builder setExpiryDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expiryDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string expiry_date = 3;</code>
       */
      public Builder clearExpiryDate() {
        
        expiryDate_ = getDefaultInstance().getExpiryDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string expiry_date = 3;</code>
       */
      public Builder setExpiryDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expiryDate_ = value;
        onChanged();
        return this;
      }

      private int cvv_ ;
      /**
       * <code>optional int32 cvv = 4;</code>
       */
      public int getCvv() {
        return cvv_;
      }
      /**
       * <code>optional int32 cvv = 4;</code>
       */
      public Builder setCvv(int value) {
        
        cvv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cvv = 4;</code>
       */
      public Builder clearCvv() {
        
        cvv_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DebitCardProtoObj)
    }

    // @@protoc_insertion_point(class_scope:DebitCardProtoObj)
    private static final applicationtier.protobuf.Debitcard.DebitCardProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Debitcard.DebitCardProtoObj();
    }

    public static applicationtier.protobuf.Debitcard.DebitCardProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DebitCardProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<DebitCardProtoObj>() {
      public DebitCardProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DebitCardProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DebitCardProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DebitCardProtoObj> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Debitcard.DebitCardProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateCardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UpdateCard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 card_id = 1;</code>
     */
    long getCardId();

    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    boolean hasCard();
    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard();
    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder();
  }
  /**
   * Protobuf type {@code UpdateCard}
   */
  public  static final class UpdateCard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UpdateCard)
      UpdateCardOrBuilder {
    // Use UpdateCard.newBuilder() to construct.
    private UpdateCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateCard() {
      cardId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpdateCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cardId_ = input.readInt64();
              break;
            }
            case 18: {
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder subBuilder = null;
              if (card_ != null) {
                subBuilder = card_.toBuilder();
              }
              card_ = input.readMessage(applicationtier.protobuf.Debitcard.DebitCardProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(card_);
                card_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Debitcard.internal_static_UpdateCard_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Debitcard.internal_static_UpdateCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Debitcard.UpdateCard.class, applicationtier.protobuf.Debitcard.UpdateCard.Builder.class);
    }

    public static final int CARD_ID_FIELD_NUMBER = 1;
    private long cardId_;
    /**
     * <code>optional int64 card_id = 1;</code>
     */
    public long getCardId() {
      return cardId_;
    }

    public static final int CARD_FIELD_NUMBER = 2;
    private applicationtier.protobuf.Debitcard.DebitCardProtoObj card_;
    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    public boolean hasCard() {
      return card_ != null;
    }
    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    public applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard() {
      return card_ == null ? applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
    }
    /**
     * <code>optional .DebitCardProtoObj card = 2;</code>
     */
    public applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder() {
      return getCard();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cardId_ != 0L) {
        output.writeInt64(1, cardId_);
      }
      if (card_ != null) {
        output.writeMessage(2, getCard());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cardId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, cardId_);
      }
      if (card_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCard());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Debitcard.UpdateCard)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Debitcard.UpdateCard other = (applicationtier.protobuf.Debitcard.UpdateCard) obj;

      boolean result = true;
      result = result && (getCardId()
          == other.getCardId());
      result = result && (hasCard() == other.hasCard());
      if (hasCard()) {
        result = result && getCard()
            .equals(other.getCard());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CARD_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCardId());
      if (hasCard()) {
        hash = (37 * hash) + CARD_FIELD_NUMBER;
        hash = (53 * hash) + getCard().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Debitcard.UpdateCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Debitcard.UpdateCard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UpdateCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UpdateCard)
        applicationtier.protobuf.Debitcard.UpdateCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Debitcard.internal_static_UpdateCard_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Debitcard.internal_static_UpdateCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Debitcard.UpdateCard.class, applicationtier.protobuf.Debitcard.UpdateCard.Builder.class);
      }

      // Construct using applicationtier.protobuf.Debitcard.UpdateCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cardId_ = 0L;

        if (cardBuilder_ == null) {
          card_ = null;
        } else {
          card_ = null;
          cardBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Debitcard.internal_static_UpdateCard_descriptor;
      }

      public applicationtier.protobuf.Debitcard.UpdateCard getDefaultInstanceForType() {
        return applicationtier.protobuf.Debitcard.UpdateCard.getDefaultInstance();
      }

      public applicationtier.protobuf.Debitcard.UpdateCard build() {
        applicationtier.protobuf.Debitcard.UpdateCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Debitcard.UpdateCard buildPartial() {
        applicationtier.protobuf.Debitcard.UpdateCard result = new applicationtier.protobuf.Debitcard.UpdateCard(this);
        result.cardId_ = cardId_;
        if (cardBuilder_ == null) {
          result.card_ = card_;
        } else {
          result.card_ = cardBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Debitcard.UpdateCard) {
          return mergeFrom((applicationtier.protobuf.Debitcard.UpdateCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Debitcard.UpdateCard other) {
        if (other == applicationtier.protobuf.Debitcard.UpdateCard.getDefaultInstance()) return this;
        if (other.getCardId() != 0L) {
          setCardId(other.getCardId());
        }
        if (other.hasCard()) {
          mergeCard(other.getCard());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Debitcard.UpdateCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Debitcard.UpdateCard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long cardId_ ;
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public long getCardId() {
        return cardId_;
      }
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public Builder setCardId(long value) {
        
        cardId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 card_id = 1;</code>
       */
      public Builder clearCardId() {
        
        cardId_ = 0L;
        onChanged();
        return this;
      }

      private applicationtier.protobuf.Debitcard.DebitCardProtoObj card_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder> cardBuilder_;
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public boolean hasCard() {
        return cardBuilder_ != null || card_ != null;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard() {
        if (cardBuilder_ == null) {
          return card_ == null ? applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
        } else {
          return cardBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public Builder setCard(applicationtier.protobuf.Debitcard.DebitCardProtoObj value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          cardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public Builder setCard(
          applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder builderForValue) {
        if (cardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          cardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public Builder mergeCard(applicationtier.protobuf.Debitcard.DebitCardProtoObj value) {
        if (cardBuilder_ == null) {
          if (card_ != null) {
            card_ =
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.newBuilder(card_).mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          cardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public Builder clearCard() {
        if (cardBuilder_ == null) {
          card_ = null;
          onChanged();
        } else {
          card_ = null;
          cardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder getCardBuilder() {
        
        onChanged();
        return getCardFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder() {
        if (cardBuilder_ != null) {
          return cardBuilder_.getMessageOrBuilder();
        } else {
          return card_ == null ?
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
        }
      }
      /**
       * <code>optional .DebitCardProtoObj card = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder> 
          getCardFieldBuilder() {
        if (cardBuilder_ == null) {
          cardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder>(
                  getCard(),
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        return cardBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UpdateCard)
    }

    // @@protoc_insertion_point(class_scope:UpdateCard)
    private static final applicationtier.protobuf.Debitcard.UpdateCard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Debitcard.UpdateCard();
    }

    public static applicationtier.protobuf.Debitcard.UpdateCard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateCard>
        PARSER = new com.google.protobuf.AbstractParser<UpdateCard>() {
      public UpdateCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UpdateCard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateCard> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateCard> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Debitcard.UpdateCard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DebitCardProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DebitCardProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCard_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017debitcard.proto\032\036google/protobuf/wrapp" +
      "ers.proto\"[\n\021DebitCardProtoObj\022\017\n\007card_i" +
      "d\030\001 \001(\003\022\023\n\013card_number\030\002 \001(\003\022\023\n\013expiry_d" +
      "ate\030\003 \001(\t\022\013\n\003cvv\030\004 \001(\005\"?\n\nUpdateCard\022\017\n\007" +
      "card_id\030\001 \001(\003\022 \n\004card\030\002 \001(\0132\022.DebitCardP" +
      "rotoObj2\232\002\n\025DebitCardProtoService\0226\n\nCre" +
      "ateCard\022\022.DebitCardProtoObj\032\022.DebitCardP" +
      "rotoObj\"\000\022H\n\023FetchCardByUsername\022\033.googl" +
      "e.protobuf.Int64Value\032\022.DebitCardProtoOb" +
      "j\"\000\0226\n\021UpdateCardDetails\022\013.UpdateCard\032\022.",
      "DebitCardProtoObj\"\000\022G\n\nDeleteCard\022\033.goog" +
      "le.protobuf.Int64Value\032\032.google.protobuf" +
      ".BoolValue\"\000B\034\n\030applicationtier.protobuf" +
      "P\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_DebitCardProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DebitCardProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DebitCardProtoObj_descriptor,
        new java.lang.String[] { "CardId", "CardNumber", "ExpiryDate", "Cvv", });
    internal_static_UpdateCard_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UpdateCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCard_descriptor,
        new java.lang.String[] { "CardId", "Card", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
