// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package applicationtier.protobuf;

public final class Request {
  private Request() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <code>optional bool isApproved = 2;</code>
     */
    boolean getIsApproved();

    /**
     * <code>optional string status = 3;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>optional string status = 3;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>optional int32 amount = 4;</code>
     */
    int getAmount();

    /**
     * <code>optional string comment = 5;</code>
     */
    java.lang.String getComment();
    /**
     * <code>optional string comment = 5;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    boolean hasRequestSender();
    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getRequestSender();
    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestSenderOrBuilder();

    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    boolean hasRequestReceiver();
    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getRequestReceiver();
    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestReceiverOrBuilder();

    /**
     * <code>optional string requestedDate = 8;</code>
     */
    java.lang.String getRequestedDate();
    /**
     * <code>optional string requestedDate = 8;</code>
     */
    com.google.protobuf.ByteString
        getRequestedDateBytes();
  }
  /**
   * Protobuf type {@code RequestProtoObj}
   */
  public  static final class RequestProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestProtoObj)
      RequestProtoObjOrBuilder {
    // Use RequestProtoObj.newBuilder() to construct.
    private RequestProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProtoObj() {
      requestId_ = 0L;
      isApproved_ = false;
      status_ = "";
      amount_ = 0;
      comment_ = "";
      requestedDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestId_ = input.readInt64();
              break;
            }
            case 16: {

              isApproved_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 32: {

              amount_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              comment_ = s;
              break;
            }
            case 50: {
              applicationtier.protobuf.User.UserProtoObj.Builder subBuilder = null;
              if (requestSender_ != null) {
                subBuilder = requestSender_.toBuilder();
              }
              requestSender_ = input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(requestSender_);
                requestSender_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              applicationtier.protobuf.User.UserProtoObj.Builder subBuilder = null;
              if (requestReceiver_ != null) {
                subBuilder = requestReceiver_.toBuilder();
              }
              requestReceiver_ = input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(requestReceiver_);
                requestReceiver_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              requestedDate_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Request.internal_static_RequestProtoObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Request.internal_static_RequestProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Request.RequestProtoObj.class, applicationtier.protobuf.Request.RequestProtoObj.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>optional int64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int ISAPPROVED_FIELD_NUMBER = 2;
    private boolean isApproved_;
    /**
     * <code>optional bool isApproved = 2;</code>
     */
    public boolean getIsApproved() {
      return isApproved_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private volatile java.lang.Object status_;
    /**
     * <code>optional string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>optional string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private int amount_;
    /**
     * <code>optional int32 amount = 4;</code>
     */
    public int getAmount() {
      return amount_;
    }

    public static final int COMMENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object comment_;
    /**
     * <code>optional string comment = 5;</code>
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      }
    }
    /**
     * <code>optional string comment = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTSENDER_FIELD_NUMBER = 6;
    private applicationtier.protobuf.User.UserProtoObj requestSender_;
    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    public boolean hasRequestSender() {
      return requestSender_ != null;
    }
    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getRequestSender() {
      return requestSender_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestSender_;
    }
    /**
     * <code>optional .UserProtoObj requestSender = 6;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestSenderOrBuilder() {
      return getRequestSender();
    }

    public static final int REQUESTRECEIVER_FIELD_NUMBER = 7;
    private applicationtier.protobuf.User.UserProtoObj requestReceiver_;
    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    public boolean hasRequestReceiver() {
      return requestReceiver_ != null;
    }
    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getRequestReceiver() {
      return requestReceiver_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestReceiver_;
    }
    /**
     * <code>optional .UserProtoObj requestReceiver = 7;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestReceiverOrBuilder() {
      return getRequestReceiver();
    }

    public static final int REQUESTEDDATE_FIELD_NUMBER = 8;
    private volatile java.lang.Object requestedDate_;
    /**
     * <code>optional string requestedDate = 8;</code>
     */
    public java.lang.String getRequestedDate() {
      java.lang.Object ref = requestedDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestedDate_ = s;
        return s;
      }
    }
    /**
     * <code>optional string requestedDate = 8;</code>
     */
    public com.google.protobuf.ByteString
        getRequestedDateBytes() {
      java.lang.Object ref = requestedDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestedDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeInt64(1, requestId_);
      }
      if (isApproved_ != false) {
        output.writeBool(2, isApproved_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
      }
      if (amount_ != 0) {
        output.writeInt32(4, amount_);
      }
      if (!getCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, comment_);
      }
      if (requestSender_ != null) {
        output.writeMessage(6, getRequestSender());
      }
      if (requestReceiver_ != null) {
        output.writeMessage(7, getRequestReceiver());
      }
      if (!getRequestedDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, requestedDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (isApproved_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isApproved_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, amount_);
      }
      if (!getCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, comment_);
      }
      if (requestSender_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getRequestSender());
      }
      if (requestReceiver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getRequestReceiver());
      }
      if (!getRequestedDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, requestedDate_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Request.RequestProtoObj)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Request.RequestProtoObj other = (applicationtier.protobuf.Request.RequestProtoObj) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && (getIsApproved()
          == other.getIsApproved());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && (getAmount()
          == other.getAmount());
      result = result && getComment()
          .equals(other.getComment());
      result = result && (hasRequestSender() == other.hasRequestSender());
      if (hasRequestSender()) {
        result = result && getRequestSender()
            .equals(other.getRequestSender());
      }
      result = result && (hasRequestReceiver() == other.hasRequestReceiver());
      if (hasRequestReceiver()) {
        result = result && getRequestReceiver()
            .equals(other.getRequestReceiver());
      }
      result = result && getRequestedDate()
          .equals(other.getRequestedDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + ISAPPROVED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsApproved());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      if (hasRequestSender()) {
        hash = (37 * hash) + REQUESTSENDER_FIELD_NUMBER;
        hash = (53 * hash) + getRequestSender().hashCode();
      }
      if (hasRequestReceiver()) {
        hash = (37 * hash) + REQUESTRECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getRequestReceiver().hashCode();
      }
      hash = (37 * hash) + REQUESTEDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestedDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Request.RequestProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestProtoObj)
        applicationtier.protobuf.Request.RequestProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Request.RequestProtoObj.class, applicationtier.protobuf.Request.RequestProtoObj.Builder.class);
      }

      // Construct using applicationtier.protobuf.Request.RequestProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        isApproved_ = false;

        status_ = "";

        amount_ = 0;

        comment_ = "";

        if (requestSenderBuilder_ == null) {
          requestSender_ = null;
        } else {
          requestSender_ = null;
          requestSenderBuilder_ = null;
        }
        if (requestReceiverBuilder_ == null) {
          requestReceiver_ = null;
        } else {
          requestReceiver_ = null;
          requestReceiverBuilder_ = null;
        }
        requestedDate_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObj_descriptor;
      }

      public applicationtier.protobuf.Request.RequestProtoObj getDefaultInstanceForType() {
        return applicationtier.protobuf.Request.RequestProtoObj.getDefaultInstance();
      }

      public applicationtier.protobuf.Request.RequestProtoObj build() {
        applicationtier.protobuf.Request.RequestProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Request.RequestProtoObj buildPartial() {
        applicationtier.protobuf.Request.RequestProtoObj result = new applicationtier.protobuf.Request.RequestProtoObj(this);
        result.requestId_ = requestId_;
        result.isApproved_ = isApproved_;
        result.status_ = status_;
        result.amount_ = amount_;
        result.comment_ = comment_;
        if (requestSenderBuilder_ == null) {
          result.requestSender_ = requestSender_;
        } else {
          result.requestSender_ = requestSenderBuilder_.build();
        }
        if (requestReceiverBuilder_ == null) {
          result.requestReceiver_ = requestReceiver_;
        } else {
          result.requestReceiver_ = requestReceiverBuilder_.build();
        }
        result.requestedDate_ = requestedDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Request.RequestProtoObj) {
          return mergeFrom((applicationtier.protobuf.Request.RequestProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Request.RequestProtoObj other) {
        if (other == applicationtier.protobuf.Request.RequestProtoObj.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getIsApproved() != false) {
          setIsApproved(other.getIsApproved());
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        if (!other.getComment().isEmpty()) {
          comment_ = other.comment_;
          onChanged();
        }
        if (other.hasRequestSender()) {
          mergeRequestSender(other.getRequestSender());
        }
        if (other.hasRequestReceiver()) {
          mergeRequestReceiver(other.getRequestReceiver());
        }
        if (!other.getRequestedDate().isEmpty()) {
          requestedDate_ = other.requestedDate_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Request.RequestProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Request.RequestProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <code>optional int64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private boolean isApproved_ ;
      /**
       * <code>optional bool isApproved = 2;</code>
       */
      public boolean getIsApproved() {
        return isApproved_;
      }
      /**
       * <code>optional bool isApproved = 2;</code>
       */
      public Builder setIsApproved(boolean value) {
        
        isApproved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isApproved = 2;</code>
       */
      public Builder clearIsApproved() {
        
        isApproved_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>optional string status = 3;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string status = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string status = 3;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 3;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string status = 3;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }

      private int amount_ ;
      /**
       * <code>optional int32 amount = 4;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <code>optional int32 amount = 4;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 amount = 4;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object comment_ = "";
      /**
       * <code>optional string comment = 5;</code>
       */
      public java.lang.String getComment() {
        java.lang.Object ref = comment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string comment = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        java.lang.Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string comment = 5;</code>
       */
      public Builder setComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 5;</code>
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 5;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comment_ = value;
        onChanged();
        return this;
      }

      private applicationtier.protobuf.User.UserProtoObj requestSender_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> requestSenderBuilder_;
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public boolean hasRequestSender() {
        return requestSenderBuilder_ != null || requestSender_ != null;
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getRequestSender() {
        if (requestSenderBuilder_ == null) {
          return requestSender_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestSender_;
        } else {
          return requestSenderBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public Builder setRequestSender(applicationtier.protobuf.User.UserProtoObj value) {
        if (requestSenderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestSender_ = value;
          onChanged();
        } else {
          requestSenderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public Builder setRequestSender(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (requestSenderBuilder_ == null) {
          requestSender_ = builderForValue.build();
          onChanged();
        } else {
          requestSenderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public Builder mergeRequestSender(applicationtier.protobuf.User.UserProtoObj value) {
        if (requestSenderBuilder_ == null) {
          if (requestSender_ != null) {
            requestSender_ =
              applicationtier.protobuf.User.UserProtoObj.newBuilder(requestSender_).mergeFrom(value).buildPartial();
          } else {
            requestSender_ = value;
          }
          onChanged();
        } else {
          requestSenderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public Builder clearRequestSender() {
        if (requestSenderBuilder_ == null) {
          requestSender_ = null;
          onChanged();
        } else {
          requestSender_ = null;
          requestSenderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getRequestSenderBuilder() {
        
        onChanged();
        return getRequestSenderFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestSenderOrBuilder() {
        if (requestSenderBuilder_ != null) {
          return requestSenderBuilder_.getMessageOrBuilder();
        } else {
          return requestSender_ == null ?
              applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestSender_;
        }
      }
      /**
       * <code>optional .UserProtoObj requestSender = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getRequestSenderFieldBuilder() {
        if (requestSenderBuilder_ == null) {
          requestSenderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  getRequestSender(),
                  getParentForChildren(),
                  isClean());
          requestSender_ = null;
        }
        return requestSenderBuilder_;
      }

      private applicationtier.protobuf.User.UserProtoObj requestReceiver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> requestReceiverBuilder_;
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public boolean hasRequestReceiver() {
        return requestReceiverBuilder_ != null || requestReceiver_ != null;
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getRequestReceiver() {
        if (requestReceiverBuilder_ == null) {
          return requestReceiver_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestReceiver_;
        } else {
          return requestReceiverBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public Builder setRequestReceiver(applicationtier.protobuf.User.UserProtoObj value) {
        if (requestReceiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          requestReceiver_ = value;
          onChanged();
        } else {
          requestReceiverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public Builder setRequestReceiver(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (requestReceiverBuilder_ == null) {
          requestReceiver_ = builderForValue.build();
          onChanged();
        } else {
          requestReceiverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public Builder mergeRequestReceiver(applicationtier.protobuf.User.UserProtoObj value) {
        if (requestReceiverBuilder_ == null) {
          if (requestReceiver_ != null) {
            requestReceiver_ =
              applicationtier.protobuf.User.UserProtoObj.newBuilder(requestReceiver_).mergeFrom(value).buildPartial();
          } else {
            requestReceiver_ = value;
          }
          onChanged();
        } else {
          requestReceiverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public Builder clearRequestReceiver() {
        if (requestReceiverBuilder_ == null) {
          requestReceiver_ = null;
          onChanged();
        } else {
          requestReceiver_ = null;
          requestReceiverBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getRequestReceiverBuilder() {
        
        onChanged();
        return getRequestReceiverFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getRequestReceiverOrBuilder() {
        if (requestReceiverBuilder_ != null) {
          return requestReceiverBuilder_.getMessageOrBuilder();
        } else {
          return requestReceiver_ == null ?
              applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : requestReceiver_;
        }
      }
      /**
       * <code>optional .UserProtoObj requestReceiver = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getRequestReceiverFieldBuilder() {
        if (requestReceiverBuilder_ == null) {
          requestReceiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  getRequestReceiver(),
                  getParentForChildren(),
                  isClean());
          requestReceiver_ = null;
        }
        return requestReceiverBuilder_;
      }

      private java.lang.Object requestedDate_ = "";
      /**
       * <code>optional string requestedDate = 8;</code>
       */
      public java.lang.String getRequestedDate() {
        java.lang.Object ref = requestedDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestedDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestedDate = 8;</code>
       */
      public com.google.protobuf.ByteString
          getRequestedDateBytes() {
        java.lang.Object ref = requestedDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestedDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestedDate = 8;</code>
       */
      public Builder setRequestedDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestedDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestedDate = 8;</code>
       */
      public Builder clearRequestedDate() {
        
        requestedDate_ = getDefaultInstance().getRequestedDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestedDate = 8;</code>
       */
      public Builder setRequestedDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestedDate_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestProtoObj)
    }

    // @@protoc_insertion_point(class_scope:RequestProtoObj)
    private static final applicationtier.protobuf.Request.RequestProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Request.RequestProtoObj();
    }

    public static applicationtier.protobuf.Request.RequestProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<RequestProtoObj>() {
      public RequestProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProtoObj> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Request.RequestProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestProtoObjListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestProtoObjList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    java.util.List<applicationtier.protobuf.Request.RequestProtoObj> 
        getRequestsList();
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    applicationtier.protobuf.Request.RequestProtoObj getRequests(int index);
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    int getRequestsCount();
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    java.util.List<? extends applicationtier.protobuf.Request.RequestProtoObjOrBuilder> 
        getRequestsOrBuilderList();
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    applicationtier.protobuf.Request.RequestProtoObjOrBuilder getRequestsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code RequestProtoObjList}
   */
  public  static final class RequestProtoObjList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestProtoObjList)
      RequestProtoObjListOrBuilder {
    // Use RequestProtoObjList.newBuilder() to construct.
    private RequestProtoObjList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProtoObjList() {
      requests_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestProtoObjList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                requests_ = new java.util.ArrayList<applicationtier.protobuf.Request.RequestProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              requests_.add(
                  input.readMessage(applicationtier.protobuf.Request.RequestProtoObj.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = java.util.Collections.unmodifiableList(requests_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Request.internal_static_RequestProtoObjList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Request.internal_static_RequestProtoObjList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Request.RequestProtoObjList.class, applicationtier.protobuf.Request.RequestProtoObjList.Builder.class);
    }

    public static final int REQUESTS_FIELD_NUMBER = 1;
    private java.util.List<applicationtier.protobuf.Request.RequestProtoObj> requests_;
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    public java.util.List<applicationtier.protobuf.Request.RequestProtoObj> getRequestsList() {
      return requests_;
    }
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    public java.util.List<? extends applicationtier.protobuf.Request.RequestProtoObjOrBuilder> 
        getRequestsOrBuilderList() {
      return requests_;
    }
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    public int getRequestsCount() {
      return requests_.size();
    }
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    public applicationtier.protobuf.Request.RequestProtoObj getRequests(int index) {
      return requests_.get(index);
    }
    /**
     * <code>repeated .RequestProtoObj requests = 1;</code>
     */
    public applicationtier.protobuf.Request.RequestProtoObjOrBuilder getRequestsOrBuilder(
        int index) {
      return requests_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < requests_.size(); i++) {
        output.writeMessage(1, requests_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < requests_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, requests_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Request.RequestProtoObjList)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Request.RequestProtoObjList other = (applicationtier.protobuf.Request.RequestProtoObjList) obj;

      boolean result = true;
      result = result && getRequestsList()
          .equals(other.getRequestsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getRequestsCount() > 0) {
        hash = (37 * hash) + REQUESTS_FIELD_NUMBER;
        hash = (53 * hash) + getRequestsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Request.RequestProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Request.RequestProtoObjList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestProtoObjList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestProtoObjList)
        applicationtier.protobuf.Request.RequestProtoObjListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObjList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObjList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Request.RequestProtoObjList.class, applicationtier.protobuf.Request.RequestProtoObjList.Builder.class);
      }

      // Construct using applicationtier.protobuf.Request.RequestProtoObjList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Request.internal_static_RequestProtoObjList_descriptor;
      }

      public applicationtier.protobuf.Request.RequestProtoObjList getDefaultInstanceForType() {
        return applicationtier.protobuf.Request.RequestProtoObjList.getDefaultInstance();
      }

      public applicationtier.protobuf.Request.RequestProtoObjList build() {
        applicationtier.protobuf.Request.RequestProtoObjList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Request.RequestProtoObjList buildPartial() {
        applicationtier.protobuf.Request.RequestProtoObjList result = new applicationtier.protobuf.Request.RequestProtoObjList(this);
        int from_bitField0_ = bitField0_;
        if (requestsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            requests_ = java.util.Collections.unmodifiableList(requests_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.requests_ = requests_;
        } else {
          result.requests_ = requestsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Request.RequestProtoObjList) {
          return mergeFrom((applicationtier.protobuf.Request.RequestProtoObjList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Request.RequestProtoObjList other) {
        if (other == applicationtier.protobuf.Request.RequestProtoObjList.getDefaultInstance()) return this;
        if (requestsBuilder_ == null) {
          if (!other.requests_.isEmpty()) {
            if (requests_.isEmpty()) {
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequestsIsMutable();
              requests_.addAll(other.requests_);
            }
            onChanged();
          }
        } else {
          if (!other.requests_.isEmpty()) {
            if (requestsBuilder_.isEmpty()) {
              requestsBuilder_.dispose();
              requestsBuilder_ = null;
              requests_ = other.requests_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requestsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRequestsFieldBuilder() : null;
            } else {
              requestsBuilder_.addAllMessages(other.requests_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Request.RequestProtoObjList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Request.RequestProtoObjList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<applicationtier.protobuf.Request.RequestProtoObj> requests_ =
        java.util.Collections.emptyList();
      private void ensureRequestsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          requests_ = new java.util.ArrayList<applicationtier.protobuf.Request.RequestProtoObj>(requests_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.Request.RequestProtoObj, applicationtier.protobuf.Request.RequestProtoObj.Builder, applicationtier.protobuf.Request.RequestProtoObjOrBuilder> requestsBuilder_;

      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.Request.RequestProtoObj> getRequestsList() {
        if (requestsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(requests_);
        } else {
          return requestsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public int getRequestsCount() {
        if (requestsBuilder_ == null) {
          return requests_.size();
        } else {
          return requestsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public applicationtier.protobuf.Request.RequestProtoObj getRequests(int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);
        } else {
          return requestsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder setRequests(
          int index, applicationtier.protobuf.Request.RequestProtoObj value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.set(index, value);
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder setRequests(
          int index, applicationtier.protobuf.Request.RequestProtoObj.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.set(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder addRequests(applicationtier.protobuf.Request.RequestProtoObj value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder addRequests(
          int index, applicationtier.protobuf.Request.RequestProtoObj value) {
        if (requestsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestsIsMutable();
          requests_.add(index, value);
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder addRequests(
          applicationtier.protobuf.Request.RequestProtoObj.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder addRequests(
          int index, applicationtier.protobuf.Request.RequestProtoObj.Builder builderForValue) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.add(index, builderForValue.build());
          onChanged();
        } else {
          requestsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder addAllRequests(
          java.lang.Iterable<? extends applicationtier.protobuf.Request.RequestProtoObj> values) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, requests_);
          onChanged();
        } else {
          requestsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder clearRequests() {
        if (requestsBuilder_ == null) {
          requests_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requestsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public Builder removeRequests(int index) {
        if (requestsBuilder_ == null) {
          ensureRequestsIsMutable();
          requests_.remove(index);
          onChanged();
        } else {
          requestsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public applicationtier.protobuf.Request.RequestProtoObj.Builder getRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public applicationtier.protobuf.Request.RequestProtoObjOrBuilder getRequestsOrBuilder(
          int index) {
        if (requestsBuilder_ == null) {
          return requests_.get(index);  } else {
          return requestsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public java.util.List<? extends applicationtier.protobuf.Request.RequestProtoObjOrBuilder> 
           getRequestsOrBuilderList() {
        if (requestsBuilder_ != null) {
          return requestsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(requests_);
        }
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public applicationtier.protobuf.Request.RequestProtoObj.Builder addRequestsBuilder() {
        return getRequestsFieldBuilder().addBuilder(
            applicationtier.protobuf.Request.RequestProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public applicationtier.protobuf.Request.RequestProtoObj.Builder addRequestsBuilder(
          int index) {
        return getRequestsFieldBuilder().addBuilder(
            index, applicationtier.protobuf.Request.RequestProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .RequestProtoObj requests = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.Request.RequestProtoObj.Builder> 
           getRequestsBuilderList() {
        return getRequestsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.Request.RequestProtoObj, applicationtier.protobuf.Request.RequestProtoObj.Builder, applicationtier.protobuf.Request.RequestProtoObjOrBuilder> 
          getRequestsFieldBuilder() {
        if (requestsBuilder_ == null) {
          requestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              applicationtier.protobuf.Request.RequestProtoObj, applicationtier.protobuf.Request.RequestProtoObj.Builder, applicationtier.protobuf.Request.RequestProtoObjOrBuilder>(
                  requests_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          requests_ = null;
        }
        return requestsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestProtoObjList)
    }

    // @@protoc_insertion_point(class_scope:RequestProtoObjList)
    private static final applicationtier.protobuf.Request.RequestProtoObjList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Request.RequestProtoObjList();
    }

    public static applicationtier.protobuf.Request.RequestProtoObjList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProtoObjList>
        PARSER = new com.google.protobuf.AbstractParser<RequestProtoObjList>() {
      public RequestProtoObjList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestProtoObjList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProtoObjList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProtoObjList> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Request.RequestProtoObjList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestProtoObjList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestProtoObjList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\032\036google/protobuf/wrapper" +
      "s.proto\032\nuser.proto\032\033google/protobuf/emp" +
      "ty.proto\"\316\001\n\017RequestProtoObj\022\021\n\trequestI" +
      "d\030\001 \001(\003\022\022\n\nisApproved\030\002 \001(\010\022\016\n\006status\030\003 " +
      "\001(\t\022\016\n\006amount\030\004 \001(\005\022\017\n\007comment\030\005 \001(\t\022$\n\r" +
      "requestSender\030\006 \001(\0132\r.UserProtoObj\022&\n\017re" +
      "questReceiver\030\007 \001(\0132\r.UserProtoObj\022\025\n\rre" +
      "questedDate\030\010 \001(\t\"9\n\023RequestProtoObjList" +
      "\022\"\n\010requests\030\001 \003(\0132\020.RequestProtoObj2\321\001\n" +
      "\023RequestProtoService\0228\n\022createRequestAsy",
      "nc\022\020.RequestProtoObj\032\020.RequestProtoObj\022F" +
      "\n\025fetchRequestByIdAsync\022\033.google.protobu" +
      "f.Int64Value\032\020.RequestProtoObj\0228\n\022update" +
      "RequestAsync\022\020.RequestProtoObj\032\020.Request" +
      "ProtoObjB\034\n\030applicationtier.protobufP\000b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          applicationtier.protobuf.User.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_RequestProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProtoObj_descriptor,
        new java.lang.String[] { "RequestId", "IsApproved", "Status", "Amount", "Comment", "RequestSender", "RequestReceiver", "RequestedDate", });
    internal_static_RequestProtoObjList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestProtoObjList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestProtoObjList_descriptor,
        new java.lang.String[] { "Requests", });
    com.google.protobuf.WrappersProto.getDescriptor();
    applicationtier.protobuf.User.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
