// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package applicationtier.protobuf;

public final class Transaction {
  private Transaction() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransactionProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    boolean hasTransactionId();
    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    com.google.protobuf.Int64Value getTransactionId();
    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    com.google.protobuf.Int64ValueOrBuilder getTransactionIdOrBuilder();

    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    boolean hasSenderUser();
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getSenderUser();
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder();

    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    boolean hasReceiverUser();
    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getReceiverUser();
    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getReceiverUserOrBuilder();

    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    boolean hasAmount();
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    com.google.protobuf.Int32Value getAmount();
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder();

    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    boolean hasDate();
    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    com.google.protobuf.StringValue getDate();
    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    com.google.protobuf.StringValueOrBuilder getDateOrBuilder();
  }
  /**
   * Protobuf type {@code TransactionProtoObj}
   */
  public  static final class TransactionProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransactionProtoObj)
      TransactionProtoObjOrBuilder {
    // Use TransactionProtoObj.newBuilder() to construct.
    private TransactionProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionProtoObj() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransactionProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (transactionId_ != null) {
                subBuilder = transactionId_.toBuilder();
              }
              transactionId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(transactionId_);
                transactionId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              applicationtier.protobuf.User.UserProtoObj.Builder subBuilder = null;
              if (senderUser_ != null) {
                subBuilder = senderUser_.toBuilder();
              }
              senderUser_ = input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(senderUser_);
                senderUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              applicationtier.protobuf.User.UserProtoObj.Builder subBuilder = null;
              if (receiverUser_ != null) {
                subBuilder = receiverUser_.toBuilder();
              }
              receiverUser_ = input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiverUser_);
                receiverUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (amount_ != null) {
                subBuilder = amount_.toBuilder();
              }
              amount_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(amount_);
                amount_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (date_ != null) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Transaction.TransactionProtoObj.class, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder.class);
    }

    public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Int64Value transactionId_;
    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    public boolean hasTransactionId() {
      return transactionId_ != null;
    }
    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    public com.google.protobuf.Int64Value getTransactionId() {
      return transactionId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : transactionId_;
    }
    /**
     * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getTransactionIdOrBuilder() {
      return getTransactionId();
    }

    public static final int SENDERUSER_FIELD_NUMBER = 2;
    private applicationtier.protobuf.User.UserProtoObj senderUser_;
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public boolean hasSenderUser() {
      return senderUser_ != null;
    }
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getSenderUser() {
      return senderUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
    }
    /**
     * <code>optional .UserProtoObj senderUser = 2;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder() {
      return getSenderUser();
    }

    public static final int RECEIVERUSER_FIELD_NUMBER = 3;
    private applicationtier.protobuf.User.UserProtoObj receiverUser_;
    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    public boolean hasReceiverUser() {
      return receiverUser_ != null;
    }
    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getReceiverUser() {
      return receiverUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : receiverUser_;
    }
    /**
     * <code>optional .UserProtoObj receiverUser = 3;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getReceiverUserOrBuilder() {
      return getReceiverUser();
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private com.google.protobuf.Int32Value amount_;
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public boolean hasAmount() {
      return amount_ != null;
    }
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public com.google.protobuf.Int32Value getAmount() {
      return amount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
    }
    /**
     * <code>optional .google.protobuf.Int32Value amount = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder() {
      return getAmount();
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private com.google.protobuf.StringValue date_;
    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    public boolean hasDate() {
      return date_ != null;
    }
    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    public com.google.protobuf.StringValue getDate() {
      return date_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : date_;
    }
    /**
     * <code>optional .google.protobuf.StringValue date = 5;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDateOrBuilder() {
      return getDate();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (transactionId_ != null) {
        output.writeMessage(1, getTransactionId());
      }
      if (senderUser_ != null) {
        output.writeMessage(2, getSenderUser());
      }
      if (receiverUser_ != null) {
        output.writeMessage(3, getReceiverUser());
      }
      if (amount_ != null) {
        output.writeMessage(4, getAmount());
      }
      if (date_ != null) {
        output.writeMessage(5, getDate());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (transactionId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTransactionId());
      }
      if (senderUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSenderUser());
      }
      if (receiverUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getReceiverUser());
      }
      if (amount_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAmount());
      }
      if (date_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getDate());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Transaction.TransactionProtoObj)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Transaction.TransactionProtoObj other = (applicationtier.protobuf.Transaction.TransactionProtoObj) obj;

      boolean result = true;
      result = result && (hasTransactionId() == other.hasTransactionId());
      if (hasTransactionId()) {
        result = result && getTransactionId()
            .equals(other.getTransactionId());
      }
      result = result && (hasSenderUser() == other.hasSenderUser());
      if (hasSenderUser()) {
        result = result && getSenderUser()
            .equals(other.getSenderUser());
      }
      result = result && (hasReceiverUser() == other.hasReceiverUser());
      if (hasReceiverUser()) {
        result = result && getReceiverUser()
            .equals(other.getReceiverUser());
      }
      result = result && (hasAmount() == other.hasAmount());
      if (hasAmount()) {
        result = result && getAmount()
            .equals(other.getAmount());
      }
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTransactionId()) {
        hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTransactionId().hashCode();
      }
      if (hasSenderUser()) {
        hash = (37 * hash) + SENDERUSER_FIELD_NUMBER;
        hash = (53 * hash) + getSenderUser().hashCode();
      }
      if (hasReceiverUser()) {
        hash = (37 * hash) + RECEIVERUSER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiverUser().hashCode();
      }
      if (hasAmount()) {
        hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAmount().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Transaction.TransactionProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransactionProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransactionProtoObj)
        applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Transaction.TransactionProtoObj.class, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder.class);
      }

      // Construct using applicationtier.protobuf.Transaction.TransactionProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (transactionIdBuilder_ == null) {
          transactionId_ = null;
        } else {
          transactionId_ = null;
          transactionIdBuilder_ = null;
        }
        if (senderUserBuilder_ == null) {
          senderUser_ = null;
        } else {
          senderUser_ = null;
          senderUserBuilder_ = null;
        }
        if (receiverUserBuilder_ == null) {
          receiverUser_ = null;
        } else {
          receiverUser_ = null;
          receiverUserBuilder_ = null;
        }
        if (amountBuilder_ == null) {
          amount_ = null;
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }
        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          date_ = null;
          dateBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObj_descriptor;
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObj getDefaultInstanceForType() {
        return applicationtier.protobuf.Transaction.TransactionProtoObj.getDefaultInstance();
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObj build() {
        applicationtier.protobuf.Transaction.TransactionProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObj buildPartial() {
        applicationtier.protobuf.Transaction.TransactionProtoObj result = new applicationtier.protobuf.Transaction.TransactionProtoObj(this);
        if (transactionIdBuilder_ == null) {
          result.transactionId_ = transactionId_;
        } else {
          result.transactionId_ = transactionIdBuilder_.build();
        }
        if (senderUserBuilder_ == null) {
          result.senderUser_ = senderUser_;
        } else {
          result.senderUser_ = senderUserBuilder_.build();
        }
        if (receiverUserBuilder_ == null) {
          result.receiverUser_ = receiverUser_;
        } else {
          result.receiverUser_ = receiverUserBuilder_.build();
        }
        if (amountBuilder_ == null) {
          result.amount_ = amount_;
        } else {
          result.amount_ = amountBuilder_.build();
        }
        if (dateBuilder_ == null) {
          result.date_ = date_;
        } else {
          result.date_ = dateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Transaction.TransactionProtoObj) {
          return mergeFrom((applicationtier.protobuf.Transaction.TransactionProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Transaction.TransactionProtoObj other) {
        if (other == applicationtier.protobuf.Transaction.TransactionProtoObj.getDefaultInstance()) return this;
        if (other.hasTransactionId()) {
          mergeTransactionId(other.getTransactionId());
        }
        if (other.hasSenderUser()) {
          mergeSenderUser(other.getSenderUser());
        }
        if (other.hasReceiverUser()) {
          mergeReceiverUser(other.getReceiverUser());
        }
        if (other.hasAmount()) {
          mergeAmount(other.getAmount());
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Transaction.TransactionProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Transaction.TransactionProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Int64Value transactionId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> transactionIdBuilder_;
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public boolean hasTransactionId() {
        return transactionIdBuilder_ != null || transactionId_ != null;
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public com.google.protobuf.Int64Value getTransactionId() {
        if (transactionIdBuilder_ == null) {
          return transactionId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : transactionId_;
        } else {
          return transactionIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public Builder setTransactionId(com.google.protobuf.Int64Value value) {
        if (transactionIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          transactionId_ = value;
          onChanged();
        } else {
          transactionIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public Builder setTransactionId(
          com.google.protobuf.Int64Value.Builder builderForValue) {
        if (transactionIdBuilder_ == null) {
          transactionId_ = builderForValue.build();
          onChanged();
        } else {
          transactionIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public Builder mergeTransactionId(com.google.protobuf.Int64Value value) {
        if (transactionIdBuilder_ == null) {
          if (transactionId_ != null) {
            transactionId_ =
              com.google.protobuf.Int64Value.newBuilder(transactionId_).mergeFrom(value).buildPartial();
          } else {
            transactionId_ = value;
          }
          onChanged();
        } else {
          transactionIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public Builder clearTransactionId() {
        if (transactionIdBuilder_ == null) {
          transactionId_ = null;
          onChanged();
        } else {
          transactionId_ = null;
          transactionIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public com.google.protobuf.Int64Value.Builder getTransactionIdBuilder() {
        
        onChanged();
        return getTransactionIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      public com.google.protobuf.Int64ValueOrBuilder getTransactionIdOrBuilder() {
        if (transactionIdBuilder_ != null) {
          return transactionIdBuilder_.getMessageOrBuilder();
        } else {
          return transactionId_ == null ?
              com.google.protobuf.Int64Value.getDefaultInstance() : transactionId_;
        }
      }
      /**
       * <code>optional .google.protobuf.Int64Value transaction_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
          getTransactionIdFieldBuilder() {
        if (transactionIdBuilder_ == null) {
          transactionIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                  getTransactionId(),
                  getParentForChildren(),
                  isClean());
          transactionId_ = null;
        }
        return transactionIdBuilder_;
      }

      private applicationtier.protobuf.User.UserProtoObj senderUser_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> senderUserBuilder_;
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public boolean hasSenderUser() {
        return senderUserBuilder_ != null || senderUser_ != null;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getSenderUser() {
        if (senderUserBuilder_ == null) {
          return senderUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
        } else {
          return senderUserBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder setSenderUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (senderUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          senderUser_ = value;
          onChanged();
        } else {
          senderUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder setSenderUser(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (senderUserBuilder_ == null) {
          senderUser_ = builderForValue.build();
          onChanged();
        } else {
          senderUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder mergeSenderUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (senderUserBuilder_ == null) {
          if (senderUser_ != null) {
            senderUser_ =
              applicationtier.protobuf.User.UserProtoObj.newBuilder(senderUser_).mergeFrom(value).buildPartial();
          } else {
            senderUser_ = value;
          }
          onChanged();
        } else {
          senderUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public Builder clearSenderUser() {
        if (senderUserBuilder_ == null) {
          senderUser_ = null;
          onChanged();
        } else {
          senderUser_ = null;
          senderUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getSenderUserBuilder() {
        
        onChanged();
        return getSenderUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getSenderUserOrBuilder() {
        if (senderUserBuilder_ != null) {
          return senderUserBuilder_.getMessageOrBuilder();
        } else {
          return senderUser_ == null ?
              applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : senderUser_;
        }
      }
      /**
       * <code>optional .UserProtoObj senderUser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getSenderUserFieldBuilder() {
        if (senderUserBuilder_ == null) {
          senderUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  getSenderUser(),
                  getParentForChildren(),
                  isClean());
          senderUser_ = null;
        }
        return senderUserBuilder_;
      }

      private applicationtier.protobuf.User.UserProtoObj receiverUser_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> receiverUserBuilder_;
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public boolean hasReceiverUser() {
        return receiverUserBuilder_ != null || receiverUser_ != null;
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getReceiverUser() {
        if (receiverUserBuilder_ == null) {
          return receiverUser_ == null ? applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : receiverUser_;
        } else {
          return receiverUserBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public Builder setReceiverUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (receiverUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiverUser_ = value;
          onChanged();
        } else {
          receiverUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public Builder setReceiverUser(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (receiverUserBuilder_ == null) {
          receiverUser_ = builderForValue.build();
          onChanged();
        } else {
          receiverUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public Builder mergeReceiverUser(applicationtier.protobuf.User.UserProtoObj value) {
        if (receiverUserBuilder_ == null) {
          if (receiverUser_ != null) {
            receiverUser_ =
              applicationtier.protobuf.User.UserProtoObj.newBuilder(receiverUser_).mergeFrom(value).buildPartial();
          } else {
            receiverUser_ = value;
          }
          onChanged();
        } else {
          receiverUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public Builder clearReceiverUser() {
        if (receiverUserBuilder_ == null) {
          receiverUser_ = null;
          onChanged();
        } else {
          receiverUser_ = null;
          receiverUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getReceiverUserBuilder() {
        
        onChanged();
        return getReceiverUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getReceiverUserOrBuilder() {
        if (receiverUserBuilder_ != null) {
          return receiverUserBuilder_.getMessageOrBuilder();
        } else {
          return receiverUser_ == null ?
              applicationtier.protobuf.User.UserProtoObj.getDefaultInstance() : receiverUser_;
        }
      }
      /**
       * <code>optional .UserProtoObj receiverUser = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getReceiverUserFieldBuilder() {
        if (receiverUserBuilder_ == null) {
          receiverUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  getReceiverUser(),
                  getParentForChildren(),
                  isClean());
          receiverUser_ = null;
        }
        return receiverUserBuilder_;
      }

      private com.google.protobuf.Int32Value amount_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> amountBuilder_;
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public boolean hasAmount() {
        return amountBuilder_ != null || amount_ != null;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32Value getAmount() {
        if (amountBuilder_ == null) {
          return amount_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
        } else {
          return amountBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder setAmount(com.google.protobuf.Int32Value value) {
        if (amountBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          amount_ = value;
          onChanged();
        } else {
          amountBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder setAmount(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (amountBuilder_ == null) {
          amount_ = builderForValue.build();
          onChanged();
        } else {
          amountBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder mergeAmount(com.google.protobuf.Int32Value value) {
        if (amountBuilder_ == null) {
          if (amount_ != null) {
            amount_ =
              com.google.protobuf.Int32Value.newBuilder(amount_).mergeFrom(value).buildPartial();
          } else {
            amount_ = value;
          }
          onChanged();
        } else {
          amountBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public Builder clearAmount() {
        if (amountBuilder_ == null) {
          amount_ = null;
          onChanged();
        } else {
          amount_ = null;
          amountBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32Value.Builder getAmountBuilder() {
        
        onChanged();
        return getAmountFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getAmountOrBuilder() {
        if (amountBuilder_ != null) {
          return amountBuilder_.getMessageOrBuilder();
        } else {
          return amount_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : amount_;
        }
      }
      /**
       * <code>optional .google.protobuf.Int32Value amount = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getAmountFieldBuilder() {
        if (amountBuilder_ == null) {
          amountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getAmount(),
                  getParentForChildren(),
                  isClean());
          amount_ = null;
        }
        return amountBuilder_;
      }

      private com.google.protobuf.StringValue date_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> dateBuilder_;
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public boolean hasDate() {
        return dateBuilder_ != null || date_ != null;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public com.google.protobuf.StringValue getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public Builder setDate(com.google.protobuf.StringValue value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public Builder setDate(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public Builder mergeDate(com.google.protobuf.StringValue value) {
        if (dateBuilder_ == null) {
          if (date_ != null) {
            date_ =
              com.google.protobuf.StringValue.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          date_ = null;
          dateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public com.google.protobuf.StringValue.Builder getDateBuilder() {
        
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>optional .google.protobuf.StringValue date = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TransactionProtoObj)
    }

    // @@protoc_insertion_point(class_scope:TransactionProtoObj)
    private static final applicationtier.protobuf.Transaction.TransactionProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Transaction.TransactionProtoObj();
    }

    public static applicationtier.protobuf.Transaction.TransactionProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<TransactionProtoObj>() {
      public TransactionProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransactionProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionProtoObj> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Transaction.TransactionProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionProtoObjListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TransactionProtoObjList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj> 
        getAllTransactionsList();
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    applicationtier.protobuf.Transaction.TransactionProtoObj getAllTransactions(int index);
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    int getAllTransactionsCount();
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    java.util.List<? extends applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder> 
        getAllTransactionsOrBuilderList();
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder getAllTransactionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TransactionProtoObjList}
   */
  public  static final class TransactionProtoObjList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TransactionProtoObjList)
      TransactionProtoObjListOrBuilder {
    // Use TransactionProtoObjList.newBuilder() to construct.
    private TransactionProtoObjList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionProtoObjList() {
      allTransactions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransactionProtoObjList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allTransactions_ = new java.util.ArrayList<applicationtier.protobuf.Transaction.TransactionProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allTransactions_.add(
                  input.readMessage(applicationtier.protobuf.Transaction.TransactionProtoObj.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allTransactions_ = java.util.Collections.unmodifiableList(allTransactions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObjList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObjList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.Transaction.TransactionProtoObjList.class, applicationtier.protobuf.Transaction.TransactionProtoObjList.Builder.class);
    }

    public static final int ALLTRANSACTIONS_FIELD_NUMBER = 1;
    private java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj> allTransactions_;
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    public java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj> getAllTransactionsList() {
      return allTransactions_;
    }
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    public java.util.List<? extends applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder> 
        getAllTransactionsOrBuilderList() {
      return allTransactions_;
    }
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    public int getAllTransactionsCount() {
      return allTransactions_.size();
    }
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    public applicationtier.protobuf.Transaction.TransactionProtoObj getAllTransactions(int index) {
      return allTransactions_.get(index);
    }
    /**
     * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
     */
    public applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder getAllTransactionsOrBuilder(
        int index) {
      return allTransactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allTransactions_.size(); i++) {
        output.writeMessage(1, allTransactions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allTransactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allTransactions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.Transaction.TransactionProtoObjList)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.Transaction.TransactionProtoObjList other = (applicationtier.protobuf.Transaction.TransactionProtoObjList) obj;

      boolean result = true;
      result = result && getAllTransactionsList()
          .equals(other.getAllTransactionsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAllTransactionsCount() > 0) {
        hash = (37 * hash) + ALLTRANSACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAllTransactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.Transaction.TransactionProtoObjList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.Transaction.TransactionProtoObjList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TransactionProtoObjList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TransactionProtoObjList)
        applicationtier.protobuf.Transaction.TransactionProtoObjListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObjList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObjList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.Transaction.TransactionProtoObjList.class, applicationtier.protobuf.Transaction.TransactionProtoObjList.Builder.class);
      }

      // Construct using applicationtier.protobuf.Transaction.TransactionProtoObjList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllTransactionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (allTransactionsBuilder_ == null) {
          allTransactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allTransactionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.Transaction.internal_static_TransactionProtoObjList_descriptor;
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObjList getDefaultInstanceForType() {
        return applicationtier.protobuf.Transaction.TransactionProtoObjList.getDefaultInstance();
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObjList build() {
        applicationtier.protobuf.Transaction.TransactionProtoObjList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.Transaction.TransactionProtoObjList buildPartial() {
        applicationtier.protobuf.Transaction.TransactionProtoObjList result = new applicationtier.protobuf.Transaction.TransactionProtoObjList(this);
        int from_bitField0_ = bitField0_;
        if (allTransactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allTransactions_ = java.util.Collections.unmodifiableList(allTransactions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allTransactions_ = allTransactions_;
        } else {
          result.allTransactions_ = allTransactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.Transaction.TransactionProtoObjList) {
          return mergeFrom((applicationtier.protobuf.Transaction.TransactionProtoObjList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.Transaction.TransactionProtoObjList other) {
        if (other == applicationtier.protobuf.Transaction.TransactionProtoObjList.getDefaultInstance()) return this;
        if (allTransactionsBuilder_ == null) {
          if (!other.allTransactions_.isEmpty()) {
            if (allTransactions_.isEmpty()) {
              allTransactions_ = other.allTransactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllTransactionsIsMutable();
              allTransactions_.addAll(other.allTransactions_);
            }
            onChanged();
          }
        } else {
          if (!other.allTransactions_.isEmpty()) {
            if (allTransactionsBuilder_.isEmpty()) {
              allTransactionsBuilder_.dispose();
              allTransactionsBuilder_ = null;
              allTransactions_ = other.allTransactions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allTransactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllTransactionsFieldBuilder() : null;
            } else {
              allTransactionsBuilder_.addAllMessages(other.allTransactions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.Transaction.TransactionProtoObjList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.Transaction.TransactionProtoObjList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj> allTransactions_ =
        java.util.Collections.emptyList();
      private void ensureAllTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allTransactions_ = new java.util.ArrayList<applicationtier.protobuf.Transaction.TransactionProtoObj>(allTransactions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.Transaction.TransactionProtoObj, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder, applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder> allTransactionsBuilder_;

      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj> getAllTransactionsList() {
        if (allTransactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allTransactions_);
        } else {
          return allTransactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public int getAllTransactionsCount() {
        if (allTransactionsBuilder_ == null) {
          return allTransactions_.size();
        } else {
          return allTransactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public applicationtier.protobuf.Transaction.TransactionProtoObj getAllTransactions(int index) {
        if (allTransactionsBuilder_ == null) {
          return allTransactions_.get(index);
        } else {
          return allTransactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder setAllTransactions(
          int index, applicationtier.protobuf.Transaction.TransactionProtoObj value) {
        if (allTransactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllTransactionsIsMutable();
          allTransactions_.set(index, value);
          onChanged();
        } else {
          allTransactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder setAllTransactions(
          int index, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder builderForValue) {
        if (allTransactionsBuilder_ == null) {
          ensureAllTransactionsIsMutable();
          allTransactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          allTransactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder addAllTransactions(applicationtier.protobuf.Transaction.TransactionProtoObj value) {
        if (allTransactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllTransactionsIsMutable();
          allTransactions_.add(value);
          onChanged();
        } else {
          allTransactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder addAllTransactions(
          int index, applicationtier.protobuf.Transaction.TransactionProtoObj value) {
        if (allTransactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllTransactionsIsMutable();
          allTransactions_.add(index, value);
          onChanged();
        } else {
          allTransactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder addAllTransactions(
          applicationtier.protobuf.Transaction.TransactionProtoObj.Builder builderForValue) {
        if (allTransactionsBuilder_ == null) {
          ensureAllTransactionsIsMutable();
          allTransactions_.add(builderForValue.build());
          onChanged();
        } else {
          allTransactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder addAllTransactions(
          int index, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder builderForValue) {
        if (allTransactionsBuilder_ == null) {
          ensureAllTransactionsIsMutable();
          allTransactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          allTransactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder addAllAllTransactions(
          java.lang.Iterable<? extends applicationtier.protobuf.Transaction.TransactionProtoObj> values) {
        if (allTransactionsBuilder_ == null) {
          ensureAllTransactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allTransactions_);
          onChanged();
        } else {
          allTransactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder clearAllTransactions() {
        if (allTransactionsBuilder_ == null) {
          allTransactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allTransactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public Builder removeAllTransactions(int index) {
        if (allTransactionsBuilder_ == null) {
          ensureAllTransactionsIsMutable();
          allTransactions_.remove(index);
          onChanged();
        } else {
          allTransactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public applicationtier.protobuf.Transaction.TransactionProtoObj.Builder getAllTransactionsBuilder(
          int index) {
        return getAllTransactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder getAllTransactionsOrBuilder(
          int index) {
        if (allTransactionsBuilder_ == null) {
          return allTransactions_.get(index);  } else {
          return allTransactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public java.util.List<? extends applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder> 
           getAllTransactionsOrBuilderList() {
        if (allTransactionsBuilder_ != null) {
          return allTransactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allTransactions_);
        }
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public applicationtier.protobuf.Transaction.TransactionProtoObj.Builder addAllTransactionsBuilder() {
        return getAllTransactionsFieldBuilder().addBuilder(
            applicationtier.protobuf.Transaction.TransactionProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public applicationtier.protobuf.Transaction.TransactionProtoObj.Builder addAllTransactionsBuilder(
          int index) {
        return getAllTransactionsFieldBuilder().addBuilder(
            index, applicationtier.protobuf.Transaction.TransactionProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .TransactionProtoObj allTransactions = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.Transaction.TransactionProtoObj.Builder> 
           getAllTransactionsBuilderList() {
        return getAllTransactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.Transaction.TransactionProtoObj, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder, applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder> 
          getAllTransactionsFieldBuilder() {
        if (allTransactionsBuilder_ == null) {
          allTransactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              applicationtier.protobuf.Transaction.TransactionProtoObj, applicationtier.protobuf.Transaction.TransactionProtoObj.Builder, applicationtier.protobuf.Transaction.TransactionProtoObjOrBuilder>(
                  allTransactions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allTransactions_ = null;
        }
        return allTransactionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TransactionProtoObjList)
    }

    // @@protoc_insertion_point(class_scope:TransactionProtoObjList)
    private static final applicationtier.protobuf.Transaction.TransactionProtoObjList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.Transaction.TransactionProtoObjList();
    }

    public static applicationtier.protobuf.Transaction.TransactionProtoObjList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionProtoObjList>
        PARSER = new com.google.protobuf.AbstractParser<TransactionProtoObjList>() {
      public TransactionProtoObjList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransactionProtoObjList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionProtoObjList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionProtoObjList> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.Transaction.TransactionProtoObjList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TransactionProtoObjList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TransactionProtoObjList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\032\036google/protobuf/wra" +
      "ppers.proto\032\nuser.proto\032\033google/protobuf" +
      "/empty.proto\"\353\001\n\023TransactionProtoObj\0223\n\016" +
      "transaction_id\030\001 \001(\0132\033.google.protobuf.I" +
      "nt64Value\022!\n\nsenderUser\030\002 \001(\0132\r.UserProt" +
      "oObj\022#\n\014receiverUser\030\003 \001(\0132\r.UserProtoOb" +
      "j\022+\n\006amount\030\004 \001(\0132\033.google.protobuf.Int3" +
      "2Value\022*\n\004date\030\005 \001(\0132\034.google.protobuf.S" +
      "tringValue\"H\n\027TransactionProtoObjList\022-\n" +
      "\017allTransactions\030\001 \003(\0132\024.TransactionProt",
      "oObj2\370\004\n\027TransactionProtoService\022D\n\026Crea" +
      "teTransactionAsync\022\024.TransactionProtoObj" +
      "\032\024.TransactionProtoObj\022N\n\031FetchTransacti" +
      "onByIdAsync\022\033.google.protobuf.Int64Value" +
      "\032\024.TransactionProtoObj\022[\n!FetchAlLTransa" +
      "ctionsBySenderAsync\022\034.google.protobuf.St" +
      "ringValue\032\030.TransactionProtoObjList\022]\n#F" +
      "etchAllTransactionsByReceiverAsync\022\034.goo" +
      "gle.protobuf.StringValue\032\030.TransactionPr" +
      "otoObjList\022`\n&FetchAlLTransactionsInvolv",
      "ingUserAsync\022\034.google.protobuf.StringVal" +
      "ue\032\030.TransactionProtoObjList\022V\n\034FetchTra" +
      "nsactionsByDateAsync\022\034.google.protobuf.S" +
      "tringValue\032\030.TransactionProtoObjList\022Q\n\026" +
      "DeleteTransactionAsync\022\033.google.protobuf" +
      ".Int64Value\032\032.google.protobuf.BoolValueB" +
      "\034\n\030applicationtier.protobufP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          applicationtier.protobuf.User.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_TransactionProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TransactionProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionProtoObj_descriptor,
        new java.lang.String[] { "TransactionId", "SenderUser", "ReceiverUser", "Amount", "Date", });
    internal_static_TransactionProtoObjList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TransactionProtoObjList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TransactionProtoObjList_descriptor,
        new java.lang.String[] { "AllTransactions", });
    com.google.protobuf.WrappersProto.getDescriptor();
    applicationtier.protobuf.User.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
