// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package applicationtier.protobuf;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserProtoObjOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserProtoObj)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>optional string full_name = 2;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>optional string full_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>optional string user_name = 3;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string user_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string password = 4;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>optional string password = 4;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    boolean hasCard();
    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard();
    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder();

    /**
     * <code>optional int32 balance = 6;</code>
     */
    int getBalance();
  }
  /**
   * Protobuf type {@code UserProtoObj}
   */
  public  static final class UserProtoObj extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserProtoObj)
      UserProtoObjOrBuilder {
    // Use UserProtoObj.newBuilder() to construct.
    private UserProtoObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserProtoObj() {
      userId_ = 0L;
      fullName_ = "";
      userName_ = "";
      password_ = "";
      balance_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserProtoObj(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fullName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 42: {
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder subBuilder = null;
              if (card_ != null) {
                subBuilder = card_.toBuilder();
              }
              card_ = input.readMessage(applicationtier.protobuf.Debitcard.DebitCardProtoObj.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(card_);
                card_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              balance_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.User.internal_static_UserProtoObj_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.User.internal_static_UserProtoObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.User.UserProtoObj.class, applicationtier.protobuf.User.UserProtoObj.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>optional int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int FULL_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fullName_;
    /**
     * <code>optional string full_name = 2;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string full_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string user_name = 3;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private volatile java.lang.Object password_;
    /**
     * <code>optional string password = 4;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARD_FIELD_NUMBER = 5;
    private applicationtier.protobuf.Debitcard.DebitCardProtoObj card_;
    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    public boolean hasCard() {
      return card_ != null;
    }
    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    public applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard() {
      return card_ == null ? applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
    }
    /**
     * <code>optional .DebitCardProtoObj card = 5;</code>
     */
    public applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder() {
      return getCard();
    }

    public static final int BALANCE_FIELD_NUMBER = 6;
    private int balance_;
    /**
     * <code>optional int32 balance = 6;</code>
     */
    public int getBalance() {
      return balance_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getFullNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fullName_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, password_);
      }
      if (card_ != null) {
        output.writeMessage(5, getCard());
      }
      if (balance_ != 0) {
        output.writeInt32(6, balance_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getFullNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fullName_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, password_);
      }
      if (card_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getCard());
      }
      if (balance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, balance_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.User.UserProtoObj)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.User.UserProtoObj other = (applicationtier.protobuf.User.UserProtoObj) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getFullName()
          .equals(other.getFullName());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && (hasCard() == other.hasCard());
      if (hasCard()) {
        result = result && getCard()
            .equals(other.getCard());
      }
      result = result && (getBalance()
          == other.getBalance());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      if (hasCard()) {
        hash = (37 * hash) + CARD_FIELD_NUMBER;
        hash = (53 * hash) + getCard().hashCode();
      }
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserProtoObj parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.User.UserProtoObj prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserProtoObj}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserProtoObj)
        applicationtier.protobuf.User.UserProtoObjOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.User.internal_static_UserProtoObj_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.User.internal_static_UserProtoObj_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.User.UserProtoObj.class, applicationtier.protobuf.User.UserProtoObj.Builder.class);
      }

      // Construct using applicationtier.protobuf.User.UserProtoObj.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        fullName_ = "";

        userName_ = "";

        password_ = "";

        if (cardBuilder_ == null) {
          card_ = null;
        } else {
          card_ = null;
          cardBuilder_ = null;
        }
        balance_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.User.internal_static_UserProtoObj_descriptor;
      }

      public applicationtier.protobuf.User.UserProtoObj getDefaultInstanceForType() {
        return applicationtier.protobuf.User.UserProtoObj.getDefaultInstance();
      }

      public applicationtier.protobuf.User.UserProtoObj build() {
        applicationtier.protobuf.User.UserProtoObj result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.User.UserProtoObj buildPartial() {
        applicationtier.protobuf.User.UserProtoObj result = new applicationtier.protobuf.User.UserProtoObj(this);
        result.userId_ = userId_;
        result.fullName_ = fullName_;
        result.userName_ = userName_;
        result.password_ = password_;
        if (cardBuilder_ == null) {
          result.card_ = card_;
        } else {
          result.card_ = cardBuilder_.build();
        }
        result.balance_ = balance_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.User.UserProtoObj) {
          return mergeFrom((applicationtier.protobuf.User.UserProtoObj)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.User.UserProtoObj other) {
        if (other == applicationtier.protobuf.User.UserProtoObj.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getFullName().isEmpty()) {
          fullName_ = other.fullName_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.hasCard()) {
          mergeCard(other.getCard());
        }
        if (other.getBalance() != 0) {
          setBalance(other.getBalance());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.User.UserProtoObj parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.User.UserProtoObj) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fullName_ = "";
      /**
       * <code>optional string full_name = 2;</code>
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string full_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string full_name = 2;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string full_name = 2;</code>
       */
      public Builder clearFullName() {
        
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string full_name = 2;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fullName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string user_name = 3;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 3;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>optional string password = 4;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password = 4;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }

      private applicationtier.protobuf.Debitcard.DebitCardProtoObj card_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder> cardBuilder_;
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public boolean hasCard() {
        return cardBuilder_ != null || card_ != null;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObj getCard() {
        if (cardBuilder_ == null) {
          return card_ == null ? applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
        } else {
          return cardBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public Builder setCard(applicationtier.protobuf.Debitcard.DebitCardProtoObj value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          card_ = value;
          onChanged();
        } else {
          cardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public Builder setCard(
          applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder builderForValue) {
        if (cardBuilder_ == null) {
          card_ = builderForValue.build();
          onChanged();
        } else {
          cardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public Builder mergeCard(applicationtier.protobuf.Debitcard.DebitCardProtoObj value) {
        if (cardBuilder_ == null) {
          if (card_ != null) {
            card_ =
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.newBuilder(card_).mergeFrom(value).buildPartial();
          } else {
            card_ = value;
          }
          onChanged();
        } else {
          cardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public Builder clearCard() {
        if (cardBuilder_ == null) {
          card_ = null;
          onChanged();
        } else {
          card_ = null;
          cardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder getCardBuilder() {
        
        onChanged();
        return getCardFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      public applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder getCardOrBuilder() {
        if (cardBuilder_ != null) {
          return cardBuilder_.getMessageOrBuilder();
        } else {
          return card_ == null ?
              applicationtier.protobuf.Debitcard.DebitCardProtoObj.getDefaultInstance() : card_;
        }
      }
      /**
       * <code>optional .DebitCardProtoObj card = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder> 
          getCardFieldBuilder() {
        if (cardBuilder_ == null) {
          cardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              applicationtier.protobuf.Debitcard.DebitCardProtoObj, applicationtier.protobuf.Debitcard.DebitCardProtoObj.Builder, applicationtier.protobuf.Debitcard.DebitCardProtoObjOrBuilder>(
                  getCard(),
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        return cardBuilder_;
      }

      private int balance_ ;
      /**
       * <code>optional int32 balance = 6;</code>
       */
      public int getBalance() {
        return balance_;
      }
      /**
       * <code>optional int32 balance = 6;</code>
       */
      public Builder setBalance(int value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 balance = 6;</code>
       */
      public Builder clearBalance() {
        
        balance_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserProtoObj)
    }

    // @@protoc_insertion_point(class_scope:UserProtoObj)
    private static final applicationtier.protobuf.User.UserProtoObj DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.User.UserProtoObj();
    }

    public static applicationtier.protobuf.User.UserProtoObj getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProtoObj>
        PARSER = new com.google.protobuf.AbstractParser<UserProtoObj>() {
      public UserProtoObj parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserProtoObj(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserProtoObj> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProtoObj> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.User.UserProtoObj getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    java.util.List<applicationtier.protobuf.User.UserProtoObj> 
        getAllUsersList();
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    applicationtier.protobuf.User.UserProtoObj getAllUsers(int index);
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    int getAllUsersCount();
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    java.util.List<? extends applicationtier.protobuf.User.UserProtoObjOrBuilder> 
        getAllUsersOrBuilderList();
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    applicationtier.protobuf.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code UserListResponse}
   */
  public  static final class UserListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserListResponse)
      UserListResponseOrBuilder {
    // Use UserListResponse.newBuilder() to construct.
    private UserListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserListResponse() {
      allUsers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allUsers_ = new java.util.ArrayList<applicationtier.protobuf.User.UserProtoObj>();
                mutable_bitField0_ |= 0x00000001;
              }
              allUsers_.add(
                  input.readMessage(applicationtier.protobuf.User.UserProtoObj.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return applicationtier.protobuf.User.internal_static_UserListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return applicationtier.protobuf.User.internal_static_UserListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              applicationtier.protobuf.User.UserListResponse.class, applicationtier.protobuf.User.UserListResponse.Builder.class);
    }

    public static final int ALLUSERS_FIELD_NUMBER = 1;
    private java.util.List<applicationtier.protobuf.User.UserProtoObj> allUsers_;
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    public java.util.List<applicationtier.protobuf.User.UserProtoObj> getAllUsersList() {
      return allUsers_;
    }
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    public java.util.List<? extends applicationtier.protobuf.User.UserProtoObjOrBuilder> 
        getAllUsersOrBuilderList() {
      return allUsers_;
    }
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    public int getAllUsersCount() {
      return allUsers_.size();
    }
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    public applicationtier.protobuf.User.UserProtoObj getAllUsers(int index) {
      return allUsers_.get(index);
    }
    /**
     * <code>repeated .UserProtoObj allUsers = 1;</code>
     */
    public applicationtier.protobuf.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
        int index) {
      return allUsers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allUsers_.size(); i++) {
        output.writeMessage(1, allUsers_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allUsers_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof applicationtier.protobuf.User.UserListResponse)) {
        return super.equals(obj);
      }
      applicationtier.protobuf.User.UserListResponse other = (applicationtier.protobuf.User.UserListResponse) obj;

      boolean result = true;
      result = result && getAllUsersList()
          .equals(other.getAllUsersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAllUsersCount() > 0) {
        hash = (37 * hash) + ALLUSERS_FIELD_NUMBER;
        hash = (53 * hash) + getAllUsersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static applicationtier.protobuf.User.UserListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(applicationtier.protobuf.User.UserListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserListResponse)
        applicationtier.protobuf.User.UserListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return applicationtier.protobuf.User.internal_static_UserListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return applicationtier.protobuf.User.internal_static_UserListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                applicationtier.protobuf.User.UserListResponse.class, applicationtier.protobuf.User.UserListResponse.Builder.class);
      }

      // Construct using applicationtier.protobuf.User.UserListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllUsersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return applicationtier.protobuf.User.internal_static_UserListResponse_descriptor;
      }

      public applicationtier.protobuf.User.UserListResponse getDefaultInstanceForType() {
        return applicationtier.protobuf.User.UserListResponse.getDefaultInstance();
      }

      public applicationtier.protobuf.User.UserListResponse build() {
        applicationtier.protobuf.User.UserListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public applicationtier.protobuf.User.UserListResponse buildPartial() {
        applicationtier.protobuf.User.UserListResponse result = new applicationtier.protobuf.User.UserListResponse(this);
        int from_bitField0_ = bitField0_;
        if (allUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allUsers_ = java.util.Collections.unmodifiableList(allUsers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allUsers_ = allUsers_;
        } else {
          result.allUsers_ = allUsersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof applicationtier.protobuf.User.UserListResponse) {
          return mergeFrom((applicationtier.protobuf.User.UserListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(applicationtier.protobuf.User.UserListResponse other) {
        if (other == applicationtier.protobuf.User.UserListResponse.getDefaultInstance()) return this;
        if (allUsersBuilder_ == null) {
          if (!other.allUsers_.isEmpty()) {
            if (allUsers_.isEmpty()) {
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllUsersIsMutable();
              allUsers_.addAll(other.allUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.allUsers_.isEmpty()) {
            if (allUsersBuilder_.isEmpty()) {
              allUsersBuilder_.dispose();
              allUsersBuilder_ = null;
              allUsers_ = other.allUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allUsersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllUsersFieldBuilder() : null;
            } else {
              allUsersBuilder_.addAllMessages(other.allUsers_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        applicationtier.protobuf.User.UserListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (applicationtier.protobuf.User.UserListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<applicationtier.protobuf.User.UserProtoObj> allUsers_ =
        java.util.Collections.emptyList();
      private void ensureAllUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allUsers_ = new java.util.ArrayList<applicationtier.protobuf.User.UserProtoObj>(allUsers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> allUsersBuilder_;

      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.User.UserProtoObj> getAllUsersList() {
        if (allUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allUsers_);
        } else {
          return allUsersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public int getAllUsersCount() {
        if (allUsersBuilder_ == null) {
          return allUsers_.size();
        } else {
          return allUsersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj getAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);
        } else {
          return allUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, applicationtier.protobuf.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.set(index, value);
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder setAllUsers(
          int index, applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(applicationtier.protobuf.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, applicationtier.protobuf.User.UserProtoObj value) {
        if (allUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllUsersIsMutable();
          allUsers_.add(index, value);
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllUsers(
          int index, applicationtier.protobuf.User.UserProtoObj.Builder builderForValue) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          allUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder addAllAllUsers(
          java.lang.Iterable<? extends applicationtier.protobuf.User.UserProtoObj> values) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allUsers_);
          onChanged();
        } else {
          allUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder clearAllUsers() {
        if (allUsersBuilder_ == null) {
          allUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public Builder removeAllUsers(int index) {
        if (allUsersBuilder_ == null) {
          ensureAllUsersIsMutable();
          allUsers_.remove(index);
          onChanged();
        } else {
          allUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder getAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public applicationtier.protobuf.User.UserProtoObjOrBuilder getAllUsersOrBuilder(
          int index) {
        if (allUsersBuilder_ == null) {
          return allUsers_.get(index);  } else {
          return allUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<? extends applicationtier.protobuf.User.UserProtoObjOrBuilder> 
           getAllUsersOrBuilderList() {
        if (allUsersBuilder_ != null) {
          return allUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allUsers_);
        }
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder addAllUsersBuilder() {
        return getAllUsersFieldBuilder().addBuilder(
            applicationtier.protobuf.User.UserProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public applicationtier.protobuf.User.UserProtoObj.Builder addAllUsersBuilder(
          int index) {
        return getAllUsersFieldBuilder().addBuilder(
            index, applicationtier.protobuf.User.UserProtoObj.getDefaultInstance());
      }
      /**
       * <code>repeated .UserProtoObj allUsers = 1;</code>
       */
      public java.util.List<applicationtier.protobuf.User.UserProtoObj.Builder> 
           getAllUsersBuilderList() {
        return getAllUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder> 
          getAllUsersFieldBuilder() {
        if (allUsersBuilder_ == null) {
          allUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              applicationtier.protobuf.User.UserProtoObj, applicationtier.protobuf.User.UserProtoObj.Builder, applicationtier.protobuf.User.UserProtoObjOrBuilder>(
                  allUsers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allUsers_ = null;
        }
        return allUsersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:UserListResponse)
    }

    // @@protoc_insertion_point(class_scope:UserListResponse)
    private static final applicationtier.protobuf.User.UserListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new applicationtier.protobuf.User.UserListResponse();
    }

    public static applicationtier.protobuf.User.UserListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserListResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserListResponse>() {
      public UserListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserListResponse> getParserForType() {
      return PARSER;
    }

    public applicationtier.protobuf.User.UserListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserProtoObj_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserProtoObj_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\036google/protobuf/wrappers.p" +
      "roto\032\017debitcard.proto\032\033google/protobuf/e" +
      "mpty.proto\"\212\001\n\014UserProtoObj\022\017\n\007user_id\030\001" +
      " \001(\003\022\021\n\tfull_name\030\002 \001(\t\022\021\n\tuser_name\030\003 \001" +
      "(\t\022\020\n\010password\030\004 \001(\t\022 \n\004card\030\005 \001(\0132\022.Deb" +
      "itCardProtoObj\022\017\n\007balance\030\006 \001(\005\"3\n\020UserL" +
      "istResponse\022\037\n\010allUsers\030\001 \003(\0132\r.UserProt" +
      "oObj2\316\003\n\020UserProtoService\022,\n\nCreateUser\022" +
      "\r.UserProtoObj\032\r.UserProtoObj\"\000\022;\n\014Fetch" +
      "AllUser\022\026.google.protobuf.Empty\032\021.UserLi",
      "stResponse\"\000\022D\n\023FetchUserByUsername\022\034.go" +
      "ogle.protobuf.StringValue\032\r.UserProtoObj" +
      "\"\000\022=\n\rFetchUserById\022\033.google.protobuf.In" +
      "t64Value\032\r.UserProtoObj\"\000\022,\n\nUpdateUser\022" +
      "\r.UserProtoObj\032\r.UserProtoObj\"\000\022G\n\nDelet" +
      "eUser\022\033.google.protobuf.Int64Value\032\032.goo" +
      "gle.protobuf.BoolValue\"\000\022S\n\026FetchBalance" +
      "ByUsername\022\034.google.protobuf.StringValue" +
      "\032\033.google.protobuf.Int32ValueB\034\n\030applica" +
      "tiontier.protobufP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          applicationtier.protobuf.Debitcard.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_UserProtoObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserProtoObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserProtoObj_descriptor,
        new java.lang.String[] { "UserId", "FullName", "UserName", "Password", "Card", "Balance", });
    internal_static_UserListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserListResponse_descriptor,
        new java.lang.String[] { "AllUsers", });
    com.google.protobuf.WrappersProto.getDescriptor();
    applicationtier.protobuf.Debitcard.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
