// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/notification.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SEP3_DataTier {
  public static partial class NotificationProtoService
  {
    static readonly string __ServiceName = "NotificationProtoService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SEP3_DataTier.NotificationProtoObj> __Marshaller_NotificationProtoObj = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SEP3_DataTier.NotificationProtoObj.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Int64Value.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.StringValue> __Marshaller_google_protobuf_StringValue = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.StringValue.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::SEP3_DataTier.NotificationProtoObjList> __Marshaller_NotificationProtoObjList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::SEP3_DataTier.NotificationProtoObjList.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.BoolValue.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SEP3_DataTier.NotificationProtoObj, global::SEP3_DataTier.NotificationProtoObj> __Method_CreateNotificationAsync = new grpc::Method<global::SEP3_DataTier.NotificationProtoObj, global::SEP3_DataTier.NotificationProtoObj>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateNotificationAsync",
        __Marshaller_NotificationProtoObj,
        __Marshaller_NotificationProtoObj);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::SEP3_DataTier.NotificationProtoObj> __Method_FetchNotificationByIdAsync = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::SEP3_DataTier.NotificationProtoObj>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FetchNotificationByIdAsync",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_NotificationProtoObj);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::SEP3_DataTier.NotificationProtoObjList> __Method_FetchAllNotificationsByReceiverAsync = new grpc::Method<global::Google.Protobuf.WellKnownTypes.StringValue, global::SEP3_DataTier.NotificationProtoObjList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FetchAllNotificationsByReceiverAsync",
        __Marshaller_google_protobuf_StringValue,
        __Marshaller_NotificationProtoObjList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SEP3_DataTier.NotificationProtoObj, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MarkAsRead = new grpc::Method<global::SEP3_DataTier.NotificationProtoObj, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MarkAsRead",
        __Marshaller_NotificationProtoObj,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::SEP3_DataTier.NotificationProtoObjList, global::Google.Protobuf.WellKnownTypes.Empty> __Method_MarkAllAsRead = new grpc::Method<global::SEP3_DataTier.NotificationProtoObjList, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MarkAllAsRead",
        __Marshaller_NotificationProtoObjList,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_DeleteNotificationAsync = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteNotificationAsync",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_google_protobuf_BoolValue);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SEP3_DataTier.NotificationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NotificationProtoService</summary>
    [grpc::BindServiceMethod(typeof(NotificationProtoService), "BindService")]
    public abstract partial class NotificationProtoServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SEP3_DataTier.NotificationProtoObj> CreateNotificationAsync(global::SEP3_DataTier.NotificationProtoObj request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SEP3_DataTier.NotificationProtoObj> FetchNotificationByIdAsync(global::Google.Protobuf.WellKnownTypes.Int64Value request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::SEP3_DataTier.NotificationProtoObjList> FetchAllNotificationsByReceiverAsync(global::Google.Protobuf.WellKnownTypes.StringValue request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> MarkAsRead(global::SEP3_DataTier.NotificationProtoObj request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> MarkAllAsRead(global::SEP3_DataTier.NotificationProtoObjList request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.BoolValue> DeleteNotificationAsync(global::Google.Protobuf.WellKnownTypes.Int64Value request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(NotificationProtoServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateNotificationAsync, serviceImpl.CreateNotificationAsync)
          .AddMethod(__Method_FetchNotificationByIdAsync, serviceImpl.FetchNotificationByIdAsync)
          .AddMethod(__Method_FetchAllNotificationsByReceiverAsync, serviceImpl.FetchAllNotificationsByReceiverAsync)
          .AddMethod(__Method_MarkAsRead, serviceImpl.MarkAsRead)
          .AddMethod(__Method_MarkAllAsRead, serviceImpl.MarkAllAsRead)
          .AddMethod(__Method_DeleteNotificationAsync, serviceImpl.DeleteNotificationAsync).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NotificationProtoServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateNotificationAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SEP3_DataTier.NotificationProtoObj, global::SEP3_DataTier.NotificationProtoObj>(serviceImpl.CreateNotificationAsync));
      serviceBinder.AddMethod(__Method_FetchNotificationByIdAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Int64Value, global::SEP3_DataTier.NotificationProtoObj>(serviceImpl.FetchNotificationByIdAsync));
      serviceBinder.AddMethod(__Method_FetchAllNotificationsByReceiverAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.StringValue, global::SEP3_DataTier.NotificationProtoObjList>(serviceImpl.FetchAllNotificationsByReceiverAsync));
      serviceBinder.AddMethod(__Method_MarkAsRead, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SEP3_DataTier.NotificationProtoObj, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.MarkAsRead));
      serviceBinder.AddMethod(__Method_MarkAllAsRead, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SEP3_DataTier.NotificationProtoObjList, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.MarkAllAsRead));
      serviceBinder.AddMethod(__Method_DeleteNotificationAsync, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Int64Value, global::Google.Protobuf.WellKnownTypes.BoolValue>(serviceImpl.DeleteNotificationAsync));
    }

  }
}
#endregion
